Repository GMLC-TDC/HELICS, pull requests merged in 2018-04, with the labels that each got.

#241 Cloning filter update
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/Filters.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/BasicHandleInfo.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/FilterFunctions.hpp
  src/helics/core/FilterInfo.hpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/core-types.hpp
  src/helics/core/helicsVersion.cpp
  src/helics/core/helicsVersion.hpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/core/FederateState-tests.cpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/FilterTests_cpp.cpp
Labels: Code Improvement, bug

#242 add Error tests and deal with duplicate names properly Issue #224
  src/helics/common/DualMappedPointerVector.hpp
  src/helics/common/DualMappedVector.hpp
  src/helics/common/MappedPointerVector.hpp
  src/helics/common/MappedVector.hpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/ErrorTests.cpp
Labels: bug

#245 New examples
  examples/CInterface/CMakeLists.txt
  examples/CInterface/comboFederates1/CMakeLists.txt
  examples/CInterface/comboFederates1/comboFed.c
  examples/CInterface/comboFederates1/openmpi-run.conf
  examples/CInterface/comboFederates1/run.sh
  examples/CInterface/comboFederates1/run3.sh
  examples/CInterface/comboFederates1/srun-mpi.conf
  examples/CInterface/messageFed1/CMakeLists.txt
  examples/CInterface/messageFed1/messageFed.c
  examples/CInterface/messageFed1/openmpi-run.conf
  examples/CInterface/messageFed1/run.sh
  examples/CInterface/messageFed1/run3.sh
  examples/CInterface/messageFed1/srun-mpi.conf
Labels: Example

#255 This adds several test identical to previous filter tests
  tests/helics/application_api/FilterTests.cpp
Labels: testing

#251 partially handle filters on message federates
  src/helics/core/ForwardingTimeCoordinator.cpp
  src/helics/core/TimeCoordinator.cpp
  tests/helics/application_api/FilterTests.cpp
Labels: bug

#258 Update readme
  README.md
Labels: Documentation

#257 version number update
  CMakeLists.txt
  appveyor.yml
  config/Doxyfile.in
  config/cmake/clang-cxx-dev-tools.cmake
  config/helics-config.h.in
  docs/installation/linux.md
  examples/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Documentation

#276 add definitions to not use experimental/any on mac platform
  src/helics/common/CMakeLists.txt
  src/helics/core/CMakeLists.txt
Labels: bug

#282 Thread safety improvements2
  CMakeLists.txt
  appveyor.yml
  src/helics/application_api/Endpoints.cpp
  src/helics/application_api/Federate.cpp
  src/helics/common/AsioServiceManager.h
  src/helics/core/BrokerBase.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommsBroker.hpp
  src/helics/core/CommsBroker_impl.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/ipc/IpcBroker.cpp
  src/helics/core/ipc/IpcBroker.h
  src/helics/core/ipc/IpcCore.cpp
  src/helics/core/ipc/IpcCore.h
  src/helics/core/tcp/TcpBroker.cpp
  src/helics/core/tcp/TcpBroker.h
  src/helics/core/tcp/TcpCore.cpp
  src/helics/core/tcp/TcpCore.h
  src/helics/core/tcp/TcpHelperClasses.cpp
  src/helics/core/tcp/TcpHelperClasses.h
  src/helics/core/udp/UdpBroker.cpp
  src/helics/core/udp/UdpBroker.h
  src/helics/core/udp/UdpCore.cpp
  src/helics/core/udp/UdpCore.h
  src/helics/core/zmq/ZmqBroker.cpp
  src/helics/core/zmq/ZmqBroker.h
  src/helics/core/zmq/ZmqCore.cpp
  src/helics/core/zmq/ZmqCore.h
  tests/helics/core/ZeromqCore-tests.cpp
Labels: Code Improvement

#285 Additional timing tests
  src/helics/core/FederateState.cpp
  tests/helics/application_api/TimingTests.cpp
Labels: bug
