Repository GMLC-TDC/HELICS, pull requests merged in 2018-12, with the labels that each got.

#522 Close routes
  src/helics/common/AsioServiceManager.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CommsBroker.hpp
  src/helics/core/CommsBroker_impl.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/ipc/IpcComms.cpp
  src/helics/core/tcp/TcpComms.cpp
  src/helics/core/tcp/TcpCommsSS.cpp
  src/helics/core/test/TestComms.cpp
  src/helics/core/udp/UdpComms.cpp
  src/helics/core/zmq/ZmqComms.cpp
  tests/helics/application_api/application-api-tests.cpp
Labels: Code Improvement

#524 Update to test files
  config/HELICSConfig.cmake.in
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/CombinationFederateTests.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/application_api/test_files/example_combo_fed.json
  tests/helics/application_api/test_files/example_filters.json
  tests/helics/apps/CMakeLists.txt
  tests/helics/apps/EchoTests.cpp
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/SourceTests.cpp
  tests/helics/apps/TracerTests.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/test-value-federate2.cpp
  tests/helics/shared_library/test-value-federate2_cpp.cpp
  tests/helics/shared_library/test_files/example_message_fed.json
  tests/helics/shared_library/test_files/example_value_fed.json
  tests/helics/test_files/example_combo_fed.json
  tests/helics/test_files/example_combo_fed.toml
  tests/helics/test_files/example_connections1.json
  tests/helics/test_files/example_connections1.toml
  tests/helics/test_files/example_connections2.json
  tests/helics/test_files/example_connections2.toml
  tests/helics/test_files/example_connections3.toml
  tests/helics/test_files/example_connections4.toml
  tests/helics/test_files/example_filters.json
  tests/helics/test_files/example_filters.toml
  tests/helics/test_files/example_message_fed.json
  tests/helics/test_files/example_message_fed.toml
  tests/helics/test_files/example_value_fed.json
  tests/helics/test_files/example_value_fed.toml
Labels: testing, ux

#528 Global values
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/Broker.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/fileConnections.hpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/core/BrokerClassTests.cpp
  tests/helics/core/CMakeLists.txt
  tests/helics/test_files/example_globals1.json
  tests/helics/test_files/example_globals1.toml
  tests/helics/test_files/example_globals2.json
  tests/helics/test_files/example_message_fed.json
  tests/helics/test_files/example_value_fed.json
  tests/helics/test_files/example_value_fed.toml
Labels: enhancement

#540 Disable building Python/Java interfaces for Travis CI code analysis runs
  .travis.yml
  README.md
Labels: testing

#539 Fix finding Matlab on Linux
  interfaces/matlab/CMakeLists.txt
Labels: Installation/build, bug

#534 Blocking finalize
  src/helics/application_api/AsyncFedCallInfo.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/core-types.hpp
  src/helics/core/test/TestComms.cpp
  src/helics/cpp98/Broker.hpp
  src/helics/cpp98/Core.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/api-data.h
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/MessageFederateKeyTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/application_api/ValueFederateTestTemplates.hpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/QueryTests.cpp
  tests/helics/shared_library/test-message-federate.cpp
Labels: bug

#543 App name fix
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/apps/MultiBroker.cpp
  src/helics/apps/Player.cpp
  src/helics/apps/helicsApp.cpp
  src/helics/apps/helicsApp.hpp
  src/helics/apps/playerMain.cpp
  src/helics/core/core-types.cpp
  src/helics/shared_api_library/ValueFederate.h
  src/helics/shared_api_library/ValueFederateExport.cpp
  tests/helics/apps/combo_tests.cpp
  tests/helics/apps/test_files/federate_config.json
  tests/helics/apps/test_files/test_HELICS_player.json
  tests/helics/apps/test_files/test_HELICS_recorder.json
Labels: bug

#549 CI build triggers
  .travis.yml
  scripts/setup-helics-ci-options.sh
  scripts/trigger-dependent-ci-builds.sh
  scripts/upload-ci-artifact.sh
Labels: Installation/build, testing

#552 Alter FindZeroMQ module to make it work better with non-system installs
  config/HELICSConfig.cmake.in
  config/cmake/FindZeroMQ.cmake
Labels: Installation/build, bug

#554 propagate the flags to newly created interfaces and create a test cas…
  src/helics/application_api/FederateInfo.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/flagOperations.hpp
  tests/helics/system_tests/flagTests.cpp
Labels: bug
