Repository GMLC-TDC/HELICS, pull requests merged in 2018-07, with the labels that each got.

#382 Set Python version to use on Travis from available pyenv versions
  .travis.yml
  scripts/install-ci-dependencies.sh
Labels: testing

#380 Additional matlab tests
  CMakeLists.txt
  swig/matlab/helicsStartup.m
  tests/matlab_helics/CMakeLists.txt
  tests/matlab_helics/messageFedTests.m
  tests/matlab_helics/messageFilterTests.m
  tests/matlab_helics/runTestsUNIX.m.in
  tests/matlab_helics/runTestsWIN32.m.in
  tests/python_helics/test_message_federate.py
  tests/python_helics/test_message_filter.py
Labels: testing

#385 Replace individual setting of HELICS_VERSION_* variables with CMake project VERSION argument
  CMakeLists.txt
Labels: Installation/build

#387 add multiline comments, 2 argument lines to player files, and a few e…
  src/helics/apps/Player.cpp
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/test_files/example5.player
  tests/helics/apps/test_files/example_comments.player
Labels: enhancement

#394 App help update
  src/helics/apps/Echo.cpp
  src/helics/apps/Player.cpp
  src/helics/apps/PrecHelper.cpp
  src/helics/apps/Recorder.cpp
  src/helics/apps/SignalGenerators.cpp
  src/helics/apps/Source.cpp
  src/helics/apps/Tracer.cpp
  src/helics/apps/appMain.cpp
  src/helics/apps/helics-broker.cpp
  src/helics/apps/helicsApp.cpp
  src/helics/apps/helicsConfigMain.cpp
  src/helics/apps/playerMain.cpp
  src/helics/apps/recorderMain.cpp
Labels: Documentation

#395 Toml file input
  ThirdParty/toml/LICENSE
  ThirdParty/toml/README.md
  ThirdParty/toml/toml.h
  src/helics/application_api/AsyncFedCallInfo.hpp
  src/helics/application_api/CombinationFederate.cpp
  src/helics/application_api/CombinationFederate.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/MessageFederate.cpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/common/CMakeLists.txt
  src/helics/common/JsonProcessingFunctions.hpp
  src/helics/common/TomlProcessingFunctions.cpp
  src/helics/common/TomlProcessingFunctions.hpp
  tests/helics/application_api/CombinationFederateTests.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/test_files/example_combo_fed.toml
  tests/helics/application_api/test_files/example_filters.toml
  tests/helics/application_api/test_files/example_message_fed.toml
  tests/helics/application_api/test_files/example_value_fed.toml
Labels: Code Improvement

#396 Subscription object callbacks
  src/helics/application_api/HelicsPrimaryTypes.hpp
  src/helics/application_api/Subscriptions.cpp
  src/helics/application_api/Subscriptions.hpp
  src/helics/apps/helicsApp.hpp
  src/helics/core/CommonCore.cpp
  src/helics/shared_api_library/ValueFederateExport.cpp
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/shared_library/test-value-federate1.cpp
  tests/java_helics/JavaHelicsApiTests.java
Labels: Code Improvement

#404 System tests
  .travis.yml
  CMakeLists.txt
  config/cmake/ucm.cmake
  src/helics/CMakeLists.txt
  src/helics/application_api/helicsTypes.hpp
  src/helics/apps/CMakeLists.txt
  src/helics/shared_api_library/CMakeLists.txt
  tests/CMakeLists.txt
  tests/helics/CMakeLists.txt
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/ErrorTests.cpp
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/system_tests/TimingTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
  tests/helics/system_tests/federateRealTimeTests.cpp
  tests/helics/system_tests/heat-transfer-tests.cpp
  tests/helics/system_tests/helics_system_tests.cpp
  tests/helics/system_tests/iterationTests.cpp
Labels: Code Improvement, bug

#401 Better app control and output
  docs/apps/App.md
  docs/apps/Broker.md
  docs/apps/Echo.md
  docs/apps/Player.md
  docs/apps/Recorder.md
  docs/apps/Source.md
  docs/apps/Tracer.md
  docs/apps/index.md
  docs/configuration/Federate.md
  docs/user-guide/index.md
  docs/user-guide/queries.md
  src/helics/application_api/Federate.cpp
  src/helics/application_api/queryFunctions.hpp
  src/helics/apps/BrokerApp.cpp
  src/helics/apps/BrokerApp.hpp
  src/helics/apps/Player.cpp
  src/helics/apps/Player.hpp
  src/helics/apps/Recorder.cpp
  src/helics/apps/Recorder.hpp
  src/helics/apps/Tracer.cpp
  src/helics/apps/helics-broker.cpp
  src/helics/common/CMakeLists.txt
  src/helics/common/fmt_format.h
  src/helics/common/fmt_ostream.h
  src/helics/core/ActionMessage.cpp
  src/helics/core/Broker.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommonCore.cpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/ForwardingTimeCoordinator.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/queryHelpers.hpp
  tests/java_helics/JavaHelicsApiTests.java
Labels: Code Improvement, Documentation

#406 Test octave build on linux
  config/cmake/FindOctave.cmake
  docs/installation/language.md
  swig/CMakeLists.txt
Labels: Interfaces

#408 Fix a potential seg fault in the shared library
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsExport.cpp
  src/helics/shared_api_library/internal/api_objects.h
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/badInputTests.cpp
Labels: bug

#405 add timing tests to shared_library tests
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/TimingTests.cpp
  tests/helics/system_tests/TimingTests.cpp
Labels: testing

#413 Compiler warnings
  src/helics/application_api/HelicsPrimaryTypes.hpp
  src/helics/application_api/helicsTypes.hpp
  src/helics/common/JsonProcessingFunctions.cpp
  src/helics/common/JsonProcessingFunctions.hpp
  src/helics/common/TomlProcessingFunctions.cpp
  src/helics/common/TomlProcessingFunctions.hpp
  src/helics/core/BrokerFactory.cpp
  src/helics/core/BrokerFactory.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/helics-time.cpp
  src/helics/core/zmq/ZmqComms.cpp
  src/helics/core/zmq/ZmqCore.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/ValueConverterTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/common/AirLockTests.cpp
  tests/helics/common/BlockingQueueTests.cpp
  tests/helics/common/DualMappedPointerVectorTests.cpp
  tests/helics/common/DualMappedVectorTests.cpp
  tests/helics/common/MappedPointerVectorTests.cpp
  tests/helics/common/MappedVectorTests.cpp
  tests/helics/common/PriorityBlockingQueueTests.cpp
  tests/helics/common/SimpleQueueTests.cpp
  tests/helics/common/TimeTests.cpp
  tests/helics/shared_library/test-message-federate.cpp
  tests/helics/shared_library/test-message-federate_cpp.cpp
  tests/helics/system_tests/heat-transfer-tests.cpp
  tests/helics/system_tests/iterationTests.cpp
Labels: Code Improvement
