Repository GMLC-TDC/HELICS, pull requests merged in 2018-02, with the labels that each got.

#155 Tests for endpoint callbacks and time Issues #142 and #140
  tests/helics/application_api/test-message-federate.cpp
  tests/helics/common/CMakeLists.txt
  tests/helics/common/TimeTests.cpp
Labels: testing

#154 Cmake updates and modifications
  .travis.yml
  CMakeLists.txt
  README.md
  config/cmake/CodeCoverage.cmake
  config/cmake/compiler_flags.cmake
  config/cmake/configGenerator.cmake
  examples/CMakeLists.txt
  src/helics/application_api/CombinationFederate.cpp
  src/helics/application_api/MessageFederate.cpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/ipc/IpcQueueHelper.h
  src/helics/core/tcp/TcpComms.cpp
  src/helics/core/udp/UdpComms.h
  tests/helics/core/IPCcore_tests.cpp
  tests/helics/core/TcpCore-tests.cpp
  tests/helics/core/UdpCore-tests.cpp
  tests/helics/core/ZeromqCore-tests.cpp
Labels: Code Improvement

#164 MPI Core
  CMakeLists.txt
  examples/messageFederates1/openmpi-run.conf
  examples/messageFederates1/srun-mpi.conf
  src/helics/core/BrokerFactory.cpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CoreFactory.cpp
  src/helics/core/mpi/MpiBroker.cpp
  src/helics/core/mpi/MpiBroker.h
  src/helics/core/mpi/MpiComms.cpp
  src/helics/core/mpi/MpiComms.h
  src/helics/core/mpi/MpiCore.cpp
  src/helics/core/mpi/MpiCore.h
  src/helics/core/mpi/MpiService.cpp
  src/helics/core/mpi/MpiService.h
  tests/helics/core/CMakeLists.txt
  tests/helics/core/MpiCore-tests.cpp
Labels: enhancement

#186 Tracer app
  ThirdParty/libguarded/guarded.hpp
  ThirdParty/libguarded/shared_guarded.hpp
  src/helics/application_api/Endpoints.cpp
  src/helics/application_api/Endpoints.hpp
  src/helics/application_api/Federate.hpp
  src/helics/apps/Echo.cpp
  src/helics/apps/Echo.hpp
  src/helics/apps/Player.cpp
  src/helics/apps/Player.hpp
  src/helics/apps/Recorder.cpp
  src/helics/apps/Recorder.hpp
  src/helics/apps/Source.cpp
  src/helics/apps/Source.hpp
  src/helics/apps/Tracer.cpp
  src/helics/apps/Tracer.hpp
  src/helics/apps/appMain.cpp
  src/helics/apps/playerMain.cpp
  src/helics/apps/recorderMain.cpp
  src/helics/common/AsioServiceManager.cpp
  src/helics/common/logger.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/Core.hpp
  tests/helics/application_api/ValueConverterTests.cpp
  tests/helics/apps/CMakeLists.txt
  tests/helics/apps/EchoTests.cpp
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/TracerTests.cpp
  tests/helics/apps/combo_tests.cpp
Labels: enhancement
