Repository GMLC-TDC/HELICS, pull requests merged in 2019-06, with the labels that each got.

#695 Remove map traits
  docs/Public_API.md
  docs/developer-guide/continuous-integration.md
  src/helics/application_api/MessageFederateManager.hpp
  src/helics/application_api/ValueFederateManager.hpp
  src/helics/apps/Recorder.cpp
  src/helics/apps/Tracer.cpp
  src/helics/apps/appMain.cpp
  src/helics/common/CMakeLists.txt
  src/helics/common/logger.cpp
  src/helics/common/logger.h
  src/helics/common/loggerCore.cpp
  src/helics/common/loggerCore.hpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.hpp
  src/helics/core/InterfaceInfo.hpp
  src/helics/core/federate_id.hpp
  src/helics/core/federate_id_extra.hpp
  src/helics/shared_api_library/helicsExport.cpp
Labels: Installation/build

#697 Move 3rd party headers to a HELICS include directory subfolder
  CMakeLists.txt
  ThirdParty/helics/external/CLI11/CLI11.hpp
  ThirdParty/helics/external/any.hpp
  ThirdParty/helics/external/filesystem.hpp
  ThirdParty/helics/external/string_view.hpp
  ThirdParty/helics/external/variant.hpp
  src/helics/application_api/HelicsPrimaryTypes.hpp
  src/helics/application_api/data_view.hpp
  src/helics/apps/helicsConfigMain.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/PublicationInfo.cpp
  src/helics/core/helicsCLI11.hpp
  src/helics/core/ipc/IpcBlockingPriorityQueue.cpp
  src/helics/core/ipc/IpcBlockingPriorityQueue.hpp
  src/helics/core/ipc/IpcBlockingPriorityQueueImpl.hpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/combo_tests.cpp
  tests/helics/apps/exeTestHelper.cpp
Labels: Installation/build

#699 Add triggering CI builds in the HELICS-Examples repository
  .travis.yml
  scripts/trigger-dependent-ci-builds.sh
Labels: Examples, enhancement, testing

#701 Clean-up the RTD navigation and fix the RTD build
  docs/doxygen/index.md
  docs/index.md
  src/helics/core/helicsCLI11.hpp
Labels: Documentation, bug

#704 Message timer fixes
  config/cmake/FindZeroMQ.cmake
  config/cmake/addZeroMQ.cmake
  src/helics/core/BrokerFactory.cpp
  src/helics/core/CoreFactory.cpp
  src/helics/core/MessageTimer.cpp
  src/helics/core/MessageTimer.hpp
  tests/helics/core/MessageTimerTests.cpp
  tests/helics/core/TestCore-tests.cpp
Labels: bug

#705 Install misc docs to the standard GNU/FHS directories
  CHANGELOG.md
  CMakeLists.txt
  README.md
Labels: Installation/build

#706 Set HELICS CMake package variables using target properties
  config/HELICSConfig.cmake.in
Labels: Installation/build

#707 Allow any value for CXX_STANDARD env var on Travis
  .travis.yml
  scripts/setup-helics-ci-options.sh
Labels: bug, testing

#708 Trigger helics-ns3 repo builds with PR variables
  scripts/trigger-dependent-ci-builds.sh
Labels: testing

#711 Update ghc::filesystem to include systemerror_r fix
  ThirdParty/helics/external/filesystem.hpp
Labels: bug

#710 Add Drone Cloud config file for ARM and ARM64 CI builds
  .ci/.drone.yml
  .travis.yml
Labels: Installation/build

#714 Remove the XCode 8.3 build for PRs to develop
  .travis.yml
Labels: testing

#713 Set dependent repo build branch to HELICS branch
  scripts/trigger-dependent-ci-builds.sh
Labels: testing

#722 Minor doc clean-up for 2.1 release
  CONTRIBUTORS.md
  README.md
  docs/Public_API.md
  docs/installation/linux.md
Labels: Documentation

#721 HELICS add_subproject test
  appveyor.yml
  scripts/setup-helics-ci-options.sh
  tests/helics/CMakeLists.txt
  tests/helics/add_subdirectory_tests/CMakeLists.txt
  tests/helics/add_subdirectory_tests/main-apps.cpp
  tests/helics/add_subdirectory_tests/main.c
  tests/helics/add_subdirectory_tests/main.cpp
  tests/helics/add_subdirectory_tests/main98.cpp
Labels: testing

#725 add some flag tests for federate level update only on change flag
  src/helics/core/NamedInputInfo.cpp
  tests/helics/system_tests/flagTests.cpp
Labels: bug

#724 Install the main swig interface files to datadir
  CMakeLists.txt
  interfaces/CMakeLists.txt
Labels: Installation/build

#726 update some documentation and other docs and version date for HELICS 2.1
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docs/ROADMAP.md
  docs/installation/language.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: Documentation
