Repository GMLC-TDC/HELICS, pull requests merged in 2019-01, with the labels that each got.

#577 Allow trigger dependent repositories step to fail
  .travis.yml
Labels: Installation/build

#584 Update variant.hpp to include constexpr fix for VS2017 15.9
  ThirdParty/helics_includes/variant.hpp
Labels: bug

#586 Doc update
  docs/installation/windows.md
  src/helics/application_api/Federate.hpp
  src/helics/application_api/MessageOperators.cpp
  src/helics/application_api/Publications.hpp
  src/helics/application_api/helicsTypes.cpp
  src/helics/apps/SignalGenerators.cpp
  src/helics/apps/SignalGenerators.hpp
  src/helics/apps/Source.hpp
  src/helics/core/Core.hpp
  src/helics/core/InterfaceInfo.hpp
  src/helics/core/JsonMapBuilder.hpp
  src/helics/core/NamedInputInfo.hpp
  src/helics/core/NetworkBrokerData.hpp
  src/helics/core/core-data.hpp
  src/helics/core/core-types.hpp
  src/helics/core/federate_id.hpp
  src/helics/core/flagOperations.hpp
  src/helics/core/helics-time.hpp
  src/helics/core/mpi/MpiBroker.h
  src/helics/core/tcp/TcpBroker.h
  src/helics/cpp98/CombinationFederate.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/cpp98/Filter.hpp
  src/helics/cpp98/Input.hpp
  src/helics/cpp98/Publication.hpp
  src/helics/cpp98/helicsExceptions.hpp
  src/helics/helics_enums.h
  src/helics/shared_api_library/ValueFederate.h
  src/helics/shared_api_library/api-data.h
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/performance_tests/multiEchoTest.cpp
Labels: Documentation

#595 Dox update3
  config/Doxyfile.in
  docs/c_api_referece.dox
  docs/index.md
  docs/mainpage.dox
  src/helics/application_api/CombinationFederate.hpp
  src/helics/application_api/Endpoints.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/FilterFederateManager.hpp
  src/helics/application_api/Filters.hpp
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/MessageFederateManager.hpp
  src/helics/application_api/Publications.hpp
  src/helics/application_api/Subscriptions.hpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/application_api/ValueFederateManager.hpp
  src/helics/application_api/queryFunctions.hpp
  src/helics/apps/BrokerApp.hpp
  src/helics/apps/Echo.hpp
  src/helics/apps/Player.hpp
  src/helics/apps/Recorder.hpp
  src/helics/apps/Source.cpp
  src/helics/apps/Source.hpp
  src/helics/apps/Tracer.cpp
  src/helics/apps/Tracer.hpp
  src/helics/apps/helicsApp.hpp
  src/helics/common/AsioServiceManager.h
  src/helics/common/BlockingPriorityQueue.hpp
  src/helics/common/BlockingQueue.hpp
  src/helics/common/DualMappedPointerVector.hpp
  src/helics/common/DualMappedVector.hpp
  src/helics/common/MappedPointerVector.hpp
  src/helics/common/MappedVector.hpp
  src/helics/common/TripWire.hpp
  src/helics/common/argParser.h
  src/helics/common/charMapper.h
  src/helics/common/logger.h
  src/helics/common/simpleQueue.hpp
  src/helics/common/stringOps.h
  src/helics/common/timeRepresentation.hpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/Broker.hpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CommsInterface.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.hpp
  src/helics/core/NetworkBrokerData.hpp
  src/helics/core/core-data.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/core/tcp/TcpHelperClasses.h
  src/helics/cpp98/Federate.hpp
  src/helics/helics_enums.h
Labels: Documentation

#597 Documentation fixes and enhancements
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  README.md
  docs/installation/linux.md
  docs/installation/mac.md
Labels: Documentation

#612 modify the export lines on the cmake
  src/helics/CMakeLists.txt
Labels: bug

#620 Mpi diagnostics
  config/cmake/compiler_flags.cmake
  src/helics/common/logger.cpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/mpi/MpiComms.cpp
  src/helics/core/mpi/MpiService.cpp
  src/helics/core/mpi/MpiService.h
Labels: bug
