Repository GMLC-TDC/HELICS, pull requests merged in 2019-12, with the labels that each got.

#937 Static analyzer fixes
  benchmarks/helics/messageSendBenchmarks.cpp
  src/helics/application_api/BrokerApp.hpp
  src/helics/application_api/CoreApp.hpp
  src/helics/application_api/Publications.hpp
  src/helics/apps/Source.cpp
  src/helics/apps/Source.hpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/BasicHandleInfo.hpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/ForwardingTimeCoordinator.hpp
  src/helics/core/TimeDependencies.hpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  tests/helics/shared_library/test-message-federate.cpp
Labels: Code Improvement

#862 New clang-format
  .clang-format
Labels: Code Improvement

#949 Always use no-hash branches for clang-format PRs
  .github/workflows/clang-format.yml
Labels: bug

#953 update .clang_format on the shared library which was distinct and fix…
  .clang-format
  src/helics/application_api/Federate.cpp
  src/helics/common/AsioContextManager.cpp
  src/helics/common/loggerCore.cpp
  src/helics/common/zmqContextManager.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/core-types.hpp
  src/helics/core/tcp/TcpBroker.h
  src/helics/shared_api_library/.clang-format
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/MessageFilters.h
  src/helics/shared_api_library/MessageFiltersExport.cpp
  src/helics/shared_api_library/ValueFederate.h
  src/helics/shared_api_library/ValueFederateExport.cpp
  src/helics/shared_api_library/api-data.h
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsCallbacks.cpp
  src/helics/shared_api_library/helicsCallbacks.h
  src/helics/shared_api_library/helicsExport.cpp
  src/helics/shared_api_library/internal/api_objects.h
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/shared_library/test-value-federate1_cpp.cpp
Labels: Code Improvement

#959 Update Azure Windows CI builds to use Python 3.5
  .ci/azure-pipelines.yml
Labels: bug, testing

#961 Fix MATLAB swig interface
  interfaces/matlab/matlab_maps.i
Labels: Interfaces, bug

#957 Fix shellcheck issues on shell scripts
  .github/actions/linux-release-builder/entrypoint.sh
  .github/workflows/interface_gen_script.sh
  .github/workflows/release-build/installer-Windows.sh
  .github/workflows/release-build/installer-macOS.sh
  .github/workflows/release-build/msvc-Windows.sh
  .github/workflows/release-build/shared-library-Linux.sh
  .github/workflows/release-build/shared-library-Windows.sh
  .github/workflows/release-build/shared-library-macOS.sh
  .github/workflows/upload-release-asset.sh
  scripts/_git-all-archive-python.sh
  scripts/_git-all-archive.sh
  scripts/cleanup-cmake.sh
  scripts/git-archive.sh
  scripts/install-ci-dependencies.sh
  scripts/install-dependency.sh
  scripts/lcov-helper.sh
  scripts/mktempdir.sh
  scripts/run-ci-tests.sh
  scripts/test_example.sh
  scripts/trigger-dependent-ci-builds.sh
  scripts/upload-ci-artifact.sh
Labels: Code Improvement

#969 Handle edge cases with git archive creation script tag arguments
  scripts/_git-all-archive.sh
Labels: bug

#974 Slow responding broker
  docs/configuration/FederateFlags.md
  docs/configuration/FederateInfo.md
  src/helics/application_api/FederateInfo.cpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/TimeoutMonitor.cpp
  src/helics/core/TimeoutMonitor.h
  src/helics/core/flagOperations.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/helics_enums.h
  tests/helics/system_tests/brokerTimeoutTests.cpp
  tests/helics/system_tests/flagTests.cpp
Labels: enhancement

#935 Add pre-commit hook to run clang-format and CMake flag to enable/disable it
  .githooks/pre-commit
  CMakeLists.txt
  config/cmake/addGitHooks.cmake
Labels: Code Improvement

#981 Fix Windows Python module extension for builds without swig
  interfaces/python/CMakeLists.txt
Labels: bug

#970 Build macOS release assets with the macOS 10.10 SDK
  .github/workflows/release-build.yml
  .github/workflows/release-build/installer-macOS.sh
  .github/workflows/setup-macos-10.10-sdk.sh
  CMakeLists.txt
Labels: Installation/build

#976 Fix minor issues with macOS install docs and add useful terminal/shell basics information
  docs/installation/mac.md
Labels: documentation

#986 Fix find Python exe and lib version mismatches
  interfaces/python/CMakeLists.txt
Labels: Installation/build, bug

#989 Fix pre-commit hook to no longer block
  .githooks/pre-commit
Labels: bug

#990 Evil tests shared lib
  .circleci/config.yml
  .codecov.yml
  config/cmake/CodeCoverage.cmake
  config/cmake/compiler_flags.cmake
  scripts/run-circleci-tests.sh
  src/docs/c_api_reference.dox
  src/helics/core/core-data.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/ValueFederate.h
  src/helics/shared_api_library/ValueFederateExport.cpp
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsExport.cpp
  src/helics/shared_api_library/internal/api_objects.h
  tests/helics/coreTypeLists.hpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/badInputTests.cpp
  tests/helics/shared_library/comboConfigTests.cpp
  tests/helics/shared_library/evilInputTests.cpp
Labels: testing
