Repository GMLC-TDC/HELICS, pull requests merged in 2019-10, with the labels that each got.

#833 Update
  src/helics/shared_api_library/MessageFederate.h
Labels: Interfaces, bug

#835 Ring echo benchmarks
  benchmarks/helics/ActionMessageBenchmarks.cpp
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/echoBenchmarks.cpp
  benchmarks/helics/ring2Benchmarks.cpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommsBroker_impl.hpp
  src/helics/core/CommsInterface.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/TimeDependencies.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/helics_enums.h
  tests/helics/CMakeLists.txt
  tests/helics/application_api/CMakeLists.txt
  tests/helics/apps/CMakeLists.txt
  tests/helics/common/CMakeLists.txt
  tests/helics/core/CMakeLists.txt
  tests/helics/performance_tests/CMakeLists.txt
  tests/helics/performance_tests/multiEchoTest.cpp
  tests/helics/performance_tests/performance-tests.cpp
  tests/helics/performance_tests/ring_tests.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/system_tests/CMakeLists.txt
Labels: Installation/build, performance/scalability, testing

#836 fix some updates and warnings on the header interface files
  interfaces/octave/octave_maps.i
  interfaces/python/python_maps.i
  interfaces/python2/python_maps2.i
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/ValueFederate.h
Labels: bug

#837 Klockwork and sanitizer fixes
  src/helics/application_api/Inputs.cpp
  src/helics/application_api/helicsPrimaryTypes.cpp
  src/helics/apps/Clone.cpp
  src/helics/apps/helics-broker-server.cpp
  src/helics/apps/helics-broker.cpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/ipc/IpcComms.cpp
  src/helics/core/ipc/IpcQueueHelper.cpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  tests/helics/application_api/PrimaryTypeConversionTests.cpp
  tests/helics/application_api/testFixtures.hpp
  tests/helics/apps/SourceTests.cpp
  tests/helics/shared_library/test-message-federate.cpp
  tests/helics/shared_library/test-message-federate_cpp.cpp
  tests/helics/system_tests/updateTests.cpp
Labels: Code Improvement, bug

#849 add echo Message Benchmark tests
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/echoMessageBenchmarks.cpp
  src/helics/application_api/Endpoints.hpp
Labels: performance/scalability

#847 Gtest update
  .circleci/config.yml
  CMakeLists.txt
  benchmarks/helics/ringBenchmarks.cpp
  config/cmake/AddGooglebenchmark.cmake
  config/cmake/AddGoogletest.cmake
  config/cmake/CheckLatestCXXStandardOption.cmake
  config/cmake/compiler_flags.cmake
  config/cmake/version_describe.cmake
  src/helics/application_api/HelicsPrimaryTypes.hpp
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/Publications.hpp
  src/helics/application_api/ValueConverter_impl.hpp
  src/helics/application_api/helicsTypes.cpp
  src/helics/application_api/helicsTypes.hpp
  src/helics/common/JsonProcessingFunctions.cpp
  src/helics/common/loggerCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/NamedInputInfo.cpp
  src/helics/core/NamedInputInfo.hpp
  src/helics/core/core-exceptions.hpp
  src/helics/core/helics-time.hpp
Labels: Installation/build

#854 Spurious removal failure
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/InterfaceInfo.cpp
  src/helics/core/NamedInputInfo.cpp
  src/helics/core/NamedInputInfo.hpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/core/InfoClass-tests.cpp
Labels: bug

#871 Add inproc core
  CMakeLists.txt
  benchmarks/helics/echoBenchmarks.cpp
  benchmarks/helics/echoMessageBenchmarks.cpp
  benchmarks/helics/messageLookupBenchmarks.cpp
  benchmarks/helics/ringBenchmarks.cpp
  config/helics-config.h.in
  src/helics/core/BrokerFactory.cpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommsBroker.cpp
  src/helics/core/CoreFactory.cpp
  src/helics/core/core-types.cpp
  src/helics/core/core-types.hpp
  src/helics/core/inproc/InprocBroker.cpp
  src/helics/core/inproc/InprocBroker.h
  src/helics/core/inproc/InprocComms.cpp
  src/helics/core/inproc/InprocComms.h
  src/helics/core/inproc/InprocCore.cpp
  src/helics/core/inproc/InprocCore.h
  src/helics/helics_enums.h
  tests/helics/core/CMakeLists.txt
  tests/helics/core/InprocCore-Tests.cpp
  tests/helics/coreTypeLists.hpp
Labels: Code Improvement

#875 Update repository for use in forked repositories that are not in Github
  .gitmodules
Labels: Installation/build, bug
