Repository GMLC-TDC/HELICS, pull requests merged in 2019-05, with the labels that each got.

#668 Cmake core inclusion update
  CMakeLists.txt
  ThirdParty/helics_includes/filesystem.hpp
  config/cmake/addBoost.cmake
  config/cmake/addJsoncpp.cmake
  config/cmake/addZeroMQ.cmake
  config/cmake/addfmt.cmake
  config/cxx14.cmake
  config/helics-config.h.in
  src/helics/application_api/CMakeLists.txt
  src/helics/application_api/FederateInfo.hpp
  src/helics/apps/BrokerApp.cpp
  src/helics/apps/BrokerApp.hpp
  src/helics/apps/MultiBroker.cpp
  src/helics/apps/helics-broker.cpp
  src/helics/common/CMakeLists.txt
  src/helics/core/BrokerFactory.cpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommsBroker.cpp
  src/helics/core/CoreFactory.cpp
  src/helics/core/core-types.cpp
  src/helics/core/helicsCLI11.hpp
  src/helics/core/tcp/TcpCommsSS.cpp
  src/helics/core/test/TestComms.cpp
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/TracerTests.cpp
  tests/helics/core/CMakeLists.txt
  tests/helics/core/CoreFactory-tests.cpp
  tests/helics/coreTypeLists.hpp
Labels: Installation/build, bug

#666 HELICS installation link update
  docs/user-guide/queries.md
  docs/user-guide/simulator_integration.md
  docs/user-guide/value_federates.md
Labels: Documentation

#673 Fix Hello World tutorial, broken Pub/Sub vs Endpoint table, and miscellaneous wording/abbreviation tweaks
  docs/developer-guide/swig.md
  docs/installation/index.md
  docs/introduction/Endpoints.md
  docs/introduction/Inputs.md
  docs/introduction/LanguageAPIs.md
  docs/introduction/Publications.md
  docs/introduction/filters.md
  docs/introduction/hello-world.md
  docs/introduction/matlab.md
  docs/introduction/pubsub-vs-message.md
  docs/introduction/python.md
  docs/introduction/terminology.md
Labels: Documentation

#678 Autoupdate git submodules
  CMakeLists.txt
  config/cmake/updateGitSubmodules.cmake
Labels: Installation/build

#681 Add tests for HELICS CMake find_package targets
  CMakeLists.txt
  config/HELICSConfig.cmake.in
  config/cmake/addfmt.cmake
  src/helics/CMakeLists.txt
  src/helics/apps/CMakeLists.txt
  src/helics/core/CMakeLists.txt
  src/helics/cpp98/CMakeLists.txt
  src/helics/cpp98/Endpoint.hpp
  src/helics/shared_api_library/CMakeLists.txt
  tests/helics/CMakeLists.txt
  tests/helics/find_package_tests/CMakeLists.txt
  tests/helics/find_package_tests/main-apps.cpp
  tests/helics/find_package_tests/main.c
  tests/helics/find_package_tests/main.cpp
  tests/helics/find_package_tests/main98.cpp
Labels: Installation/build

#683 Cmake version updates
  CMakeLists.txt
  appveyor.yml
  config/cmake/CheckLatestCXXStandardOption.cmake
  config/cmake/addBoost.cmake
  config/cmake/compiler_flags.cmake
  src/helics/application_api/Federate.cpp
  src/helics/application_api/HelicsPrimaryTypes.hpp
  src/helics/application_api/Inputs.cpp
  src/helics/core/CMakeLists.txt
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/updateTests.cpp
Labels: Installation/build, bug

#686 Helics subproject
  CMakeLists.txt
  ThirdParty/CLI11/CLI11.hpp
  config/cmake/AddGoogletest.cmake
  config/cmake/buildlibZMQ.cmake
  config/cmake/configGenerator.cmake
  config/cmake/updateGitSubmodules.cmake
  interfaces/CMakeLists.txt
  interfaces/python2/CMakeLists.txt
  src/helics/CMakeLists.txt
  src/helics/apps/CMakeLists.txt
  src/helics/common/CMakeLists.txt
  tests/helics/application_api/ValueConverterTests.cpp
  tests/helics/application_api/data_viewTests.cpp
  tests/helics/apps/CMakeLists.txt
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/combo_tests.cpp
  tests/helics/common/BlockingQueueTests.cpp
  tests/helics/common/DualMappedPointerVectorTests.cpp
  tests/helics/common/MappedPointerVectorTests.cpp
  tests/helics/common/MappedVectorTests.cpp
  tests/helics/common/SimpleQueueTests.cpp
  tests/helics/core/ActionMessage-tests.cpp
  tests/helics/core/FederateState-tests.cpp
  tests/helics/core/InfoClass-tests.cpp
  tests/helics/core/TcpCore-tests.cpp
  tests/helics/core/TcpSSCore-tests.cpp
  tests/helics/core/UdpCore-tests.cpp
  tests/helics/core/ZeromqCore-tests.cpp
  tests/helics/core/data-block-tests.cpp
  tests/helics/shared_library/test-value-federate1.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/system_tests/TimingTests.cpp
Labels: Installation/build

#688 Run packaging tests on one build configuration
  .travis.yml
  appveyor.yml
  scripts/install-ci-dependencies.sh
  scripts/setup-helics-ci-options.sh
  tests/helics/CMakeLists.txt
Labels: bug, testing

#687 Add sstream header to JsonProcessingFunctions
  src/helics/application_api/queryFunctions.cpp
  src/helics/common/JsonProcessingFunctions.cpp
Labels: bug

#694 Make the compile_flags_target work when HELICS is used as a subproject.
  CMakeLists.txt
  config/cmake/addlibzmq.cmake
  config/cmake/compiler_flags.cmake
Labels: Installation/build
