Repository GMLC-TDC/HELICS, pull requests merged in 2019-07, with the labels that each got.

#730 System tests to google tests
  tests/helics/CMakeLists.txt
  tests/helics/application_api/testFixtures.cpp
  tests/helics/common/common-tests.cpp
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/system_tests/TimingTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
  tests/helics/system_tests/federateRealTimeTests.cpp
  tests/helics/system_tests/flagTests.cpp
  tests/helics/system_tests/heat-transfer-tests.cpp
  tests/helics/system_tests/helics_system_tests.cpp
  tests/helics/system_tests/iterationTests.cpp
  tests/helics/system_tests/networkTests.cpp
  tests/helics/system_tests/updateTests.cpp
Labels: testing

#733 Test issue fixes
  .ci/undef_blacklist.txt
  scripts/.travis-tsan.yml
  scripts/ubsan-cache.cmake
  src/helics/common/JsonProcessingFunctions.cpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommsInterface.cpp
  src/helics/core/CommsInterface.hpp
  src/helics/core/tcp/TcpComms.cpp
  src/helics/core/tcp/TcpComms.h
  src/helics/core/tcp/TcpCommsCommon.cpp
  src/helics/core/tcp/TcpCommsCommon.h
  src/helics/core/tcp/TcpCommsSS.cpp
  src/helics/core/tcp/TcpCommsSS.h
  src/helics/core/zmq/ZmqCommsSS.cpp
  src/helics/core/zmq/ZmqCommsSS.h
  tests/helics/core/CMakeLists.txt
  tests/helics/core/ZeromqSSCore-tests.cpp
  tests/helics/shared_library/ctestFixtures.cpp
  tests/helics/shared_library/ctestFixtures.hpp
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/ErrorTests.cpp
Labels: bug

#737 Broker version return
  src/helics/apps/CMakeLists.txt
  src/helics/apps/appMain.cpp
  src/helics/apps/helics-broker.cpp
  tests/helics/apps/CMakeLists.txt
Labels: bug

#723 Set SO version for HELICS shared libraries
  src/helics/CMakeLists.txt
  src/helics/shared_api_library/CMakeLists.txt
Labels: Installation/build

#741 set the maxTime in C++ and C to be consistent with eachother, meani…
  CHANGELOG.md
  src/helics/common/timeRepresentation.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/api-data.h
  src/helics/shared_api_library/helics.h
  tests/helics/common/TimeTests.cpp
  tests/helics/shared_library/TimingTests.cpp
Labels: bug

#739 Json aggregate output
  docs/user-guide/queries.md
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Inputs.cpp
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/application_api/ValueFederateManager.hpp
  src/helics/application_api/queryFunctions.cpp
  src/helics/application_api/queryFunctions.hpp
  src/helics/apps/appMain.cpp
  src/helics/apps/helics-broker.cpp
  src/helics/common/CMakeLists.txt
  src/helics/common/JsonBuilder.cpp
  src/helics/common/JsonBuilder.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CoreBroker.hpp
  src/helics/core/JsonMapBuilder.cpp
  src/helics/cpp98/Federate.hpp
  src/helics/cpp98/Input.hpp
  src/helics/cpp98/ValueFederate.hpp
  src/helics/shared_api_library/ValueFederate.h
  src/helics/shared_api_library/ValueFederateExport.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/subPubObjectTests.cpp
  tests/helics/shared_library/test-value-federate2.cpp
  tests/helics/shared_library/test-value-federate2_cpp.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/test_files/example_pub_input1.json
  tests/helics/test_files/example_pub_input2.json
Labels: enhancement

#756 Include licenses for 3rd party libraries with HELICS installations
  CMakeLists.txt
  config/cmake/combineLicenses.cmake
Labels: Installation/build
