Repository GMLC-TDC/HELICS, pull requests merged in 2019-09, with the labels that each got.

#797 Warnings and 32 bit
  .ci/.drone.yml
  examples/comboFederates1/comboFed.cpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/ValueConverter_impl.hpp
  src/helics/apps/BrokerServer.cpp
  src/helics/apps/Echo.hpp
  src/helics/apps/Recorder.hpp
  src/helics/apps/helics-broker.cpp
  src/helics/common/logger.h
  src/helics/core/ActionMessage.cpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/HandleManager.cpp
  src/helics/core/federate_id.hpp
  src/helics/core/zmq/ZmqCommsCommon.h
  src/helics/core/zmq/ZmqCommsSS.h
  tests/helics/CMakeLists.txt
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/testFixtures.hpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/TimingTests.cpp
  tests/helics/shared_library/cpptestFixtures.hpp
  tests/helics/shared_library/ctestFixtures.cpp
  tests/helics/shared_library/ctestFixtures.hpp
  tests/helics/shared_library/test-message-federate.cpp
  tests/helics/shared_library/test-value-federate1.cpp
  tests/helics/shared_library/test-value-federate2.cpp
Labels: Code Improvement, bug

#801 Apps test to gtest
  scripts/run-nighly-circleci-tests.sh
  tests/helics/CMakeLists.txt
  tests/helics/apps/BrokerServerTests.cpp
  tests/helics/apps/CMakeLists.txt
  tests/helics/apps/CloneTests.cpp
  tests/helics/apps/EchoTests.cpp
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/SourceTests.cpp
  tests/helics/apps/TracerTests.cpp
  tests/helics/apps/combo_tests.cpp
  tests/helics/apps/exeTestHelper.h
  tests/helics/apps/helics_apps_tests.cpp
  tests/helics/apps/multi_player_tests.cpp
  tests/helics/apps/multi_tests.cpp
  tests/helics/core/TcpCore-tests.cpp
Labels: testing

#802 Race cond fix in queries
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
Labels: bug

#758 Logging api enhancement
  CHANGELOG.md
  CMakeLists.txt
  docs/Public_API.md
  docs/ROADMAP.md
  examples/comboFederates1/comboFed.cpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/common/logger.cpp
  src/helics/common/logger.h
  src/helics/common/loggerCore.cpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/BasicHandleInfo.hpp
  src/helics/core/Broker.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/EndpointInfo.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/FilterCoordinator.hpp
  src/helics/core/FilterInfo.hpp
  src/helics/core/NamedInputInfo.hpp
  src/helics/core/PublicationInfo.hpp
  src/helics/core/TimeDependencies.hpp
  src/helics/core/UnknownHandleManager.hpp
  src/helics/core/basic_core_types.hpp
  src/helics/core/core-data.hpp
  src/helics/core/core-types.hpp
  src/helics/core/federate_id.cpp
  src/helics/core/federate_id.hpp
  src/helics/core/federate_id_extra.hpp
  src/helics/core/global_federate_id.hpp
  src/helics/core/helicsVersion.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/helics_enums.h
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsCallbacks.cpp
  src/helics/shared_api_library/helicsCallbacks.h
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/LoggingTests.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/loggingTests.cpp
Labels: enhancement

#808 Doc updates
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTORS.md
  README.md
  docs/CMakeLists.txt
  docs/Public_API.md
  docs/ROADMAP.md
  docs/apps/App.md
  docs/conf.py
  docs/docker.md
  docs/img/timing_fed_setup.png
  docs/index.md
  docs/requirements.txt
  docs/user-guide/index.md
  docs/user-guide/logging.md
  docs/user-guide/timing.md
  docs/user-guide/timing_exercise.md
  docs/user-guide/timing_exercise_answers.md
  examples/CMakeLists.txt
  examples/CppInterface/nonlings_fed1.cpp
  examples/CppInterface/nonlings_fed2.cpp
  src/docs/c_api_reference.dox
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/application_api/helicsTypes.hpp
  src/helics/apps/BrokerApp.cpp
  src/helics/apps/BrokerApp.hpp
  src/helics/common/logger.h
  src/helics/core/BrokerBase.hpp
  src/helics/core/core-data.hpp
  src/helics/core/federate_id.hpp
  src/helics/core/global_federate_id.hpp
  src/helics/cpp98/Broker.hpp
  src/helics/cpp98/CombinationFederate.hpp
  src/helics/cpp98/Core.hpp
  src/helics/cpp98/Endpoint.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/cpp98/Filter.hpp
  src/helics/cpp98/Input.hpp
  src/helics/cpp98/MessageFederate.hpp
  src/helics/cpp98/Publication.hpp
  src/helics/cpp98/ValueFederate.hpp
  src/helics/cpp98/config.hpp
  src/helics/cpp98/helicsExceptions.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsCallbacks.cpp
  src/helics/shared_api_library/helicsCallbacks.h
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/shared_library/cpptestFixtures.hpp
  tests/helics/shared_library/loggingTests.cpp
  tests/helics/shared_library/test-message-federate_cpp.cpp
  tests/helics/shared_library/test-value-federate2_cpp.cpp
Labels: Documentation

#817 fix for the libzmq on mingw
  CMakeLists.txt
  config/cmake/addlibzmq.cmake
Labels: bug

#823 Broker timeout
  CHANGELOG.md
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommsBroker.hpp
  src/helics/core/CommsBroker_impl.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/TimeoutMonitor.cpp
  src/helics/core/TimeoutMonitor.h
  src/helics/core/flagOperations.hpp
  src/helics/core/test/TestComms.cpp
  src/helics/core/test/TestComms.h
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/brokerTimeoutTests.cpp
Labels: enhancement

#824 Fix an issue with very small periods and large time requested
  src/helics/core/TimeCoordinator.cpp
  tests/helics/system_tests/TimingTests2.cpp
Labels: bug

#827 Shared lib test to gtest
  .circleci/asan_blacklist.txt
  scripts/run-nighly-circleci-tests.sh
  tests/helics/CMakeLists.txt
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/QueryTests.cpp
  tests/helics/shared_library/TimingTests.cpp
  tests/helics/shared_library/badInputTests.cpp
  tests/helics/shared_library/comboConfigTests.cpp
  tests/helics/shared_library/ctestFixtures.cpp
  tests/helics/shared_library/ctestFixtures.hpp
  tests/helics/shared_library/loggingTests.cpp
  tests/helics/shared_library/shared-library-tests.cpp
  tests/helics/shared_library/test-message-federate.cpp
  tests/helics/shared_library/test-value-federate1.cpp
  tests/helics/shared_library/test-value-federate2.cpp
Labels: testing

#829 App api to gtest
  scripts/run-nighly-circleci-tests.sh
  src/helics/core/TimeoutMonitor.cpp
  tests/helics/CMakeLists.txt
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/CombinationFederateTests.cpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/LoggingTests.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/MessageFederateKeyTests.cpp
  tests/helics/application_api/PrimaryTypeConversionTests.cpp
  tests/helics/application_api/ValueConverterTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateDualTransfer.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/application_api/ValueFederateSingleTransfer.cpp
  tests/helics/application_api/ValueFederateTestTemplates.hpp
  tests/helics/application_api/application-api-tests.cpp
  tests/helics/application_api/data_viewTests.cpp
  tests/helics/application_api/subPubObjectTests.cpp
  tests/helics/application_api/testFixtures.hpp
  tests/helics/apps/CMakeLists.txt
  tests/helics/core/CMakeLists.txt
  tests/helics/core/MessageTimerTests.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/TimingTests.cpp
  tests/helics/system_tests/federateRealTimeTests.cpp
  tests/helics/system_tests/iterationTests.cpp
Labels: testing
