Repository GMLC-TDC/HELICS, pull requests merged in 2019-11, with the labels that each got.

#878 Query available queries
  docs/user-guide/queries.md
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: enhancement

#880 Filter benchmark
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/EchoMessage.hpp
  benchmarks/helics/echoMessageBenchmarks.cpp
  benchmarks/helics/filterBenchmarks.cpp
Labels: performance/scalability

#888 Update the Windows installer release build action
  .github/workflows/release-build.yml
Labels: Installation/build

#887 Warning fixes
  .circleci/config.yml
  .circleci/tsan_suppression.txt
  .travis.yml
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTORS.md
  ThirdParty/cppzmq/zmq_addon.hpp
  benchmarks/helics/echoBenchmarks.cpp
  benchmarks/helics/messageLookupBenchmarks.cpp
  config/cmake/AddGooglebenchmark.cmake
  config/cmake/addlibzmq.cmake
  config/cmake/copy_key_files.cmake
  docs/Public_API.md
  docs/ROADMAP.md
  examples/CppInterface/CMakeLists.txt
  examples/comboFederates1/CMakeLists.txt
  interfaces/csharp/CMakeLists.txt
  interfaces/java/CMakeLists.txt
  interfaces/java/helicsJava.i
  interfaces/python/CMakeLists.txt
  interfaces/python2/CMakeLists.txt
  scripts/setup-helics-ci-options.sh
  src/helics/application_api/CoreApp.cpp
  src/helics/application_api/FilterOperations.cpp
  src/helics/apps/helicsApp.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/NetworkCommsInterface.cpp
  src/helics/core/udp/UdpComms.cpp
  src/helics/core/zmq/ZmqCommsSS.cpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/apps/CMakeLists.txt
  tests/helics/apps/PlayerTests.cpp
  tests/helics/core/UdpCore-tests.cpp
  tests/helics/core/data-block-tests.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/java/CMakeLists.txt
Labels: Code Improvement, Installation/build, testing

#884 Add benchmarks varying message size and count
  benchmarks/helics/messageSendBenchmarks.cpp
Labels: performance/scalability

#890 fix missing return value in psuedo header for the CPP shared library …
  src/helics/cxx_shared_library/BrokerFactory.hpp
Labels: bug

#896 Update some CMake option names to use their new HELICS_ name
  CMakeLists.txt
  config/Docker/Dockerfile-HELICS
Labels: bug

#895 Add macOS installers and Linux shared library to release build workflow
  .github/workflows/release-build.yml
Labels: Installation/build

#894 Update changelog, release notes, and other assorted docs in preparation for release
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  docs/Public_API.md
  docs/ROADMAP.md
Labels: Documentation

#907 Disable asio option
  CHANGELOG.md
  CMakeLists.txt
  config/helics-config.h.in
  docs/installation/helics_cmake_options.md
  docs/installation/index.md
  src/helics/application_api/FederateInfo.cpp
  src/helics/common/CMakeLists.txt
  src/helics/core/BrokerBase.cpp
  src/helics/core/CMakeLists.txt
  src/helics/core/FederateState.cpp
  src/helics/core/MessageTimer.hpp
  src/helics/core/NetworkBrokerData.cpp
  tests/helics/core/CMakeLists.txt
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/TimingTests.cpp
  tests/helics/system_tests/networkTests.cpp
Labels: Installation/build, enhancement

#910 clean up some of the core options
  CMakeLists.txt
  benchmarks/helics/CMakeLists.txt
  src/helics/common/CMakeLists.txt
  src/helics/core/CMakeLists.txt
  tests/helics/coreTypeLists.hpp
Labels: Installation/build

#912 Update Travis XCode 8.3 build to XCode 9.4
  .travis.yml
Labels: testing

#913 Update the release builds workflow
  .github/actions/linux-release-builder/Dockerfile
  .github/actions/linux-release-builder/action.yml
  .github/actions/linux-release-builder/entrypoint.sh
  .github/workflows/release-build.yml
  .github/workflows/release-build/installer-Windows.sh
  .github/workflows/release-build/installer-macOS.sh
  .github/workflows/release-build/msvc-Windows.sh
  .github/workflows/release-build/shared-library-Linux.sh
  .github/workflows/release-build/shared-library-Windows.sh
  .github/workflows/release-build/shared-library-macOS.sh
  CMakeLists.txt
  config/cmake/addlibzmq.cmake
  docs/installation/helics_cmake_options.md
Labels: Code Improvement, Installation/build, bug, documentation

#916 Release docs
  .github/actions/linux-release-builder/Dockerfile
  .github/actions/linux-release-builder/action.yml
  .github/actions/linux-release-builder/entrypoint.sh
  .github/workflows/release-build.yml
  .github/workflows/release-build/installer-Windows.sh
  .github/workflows/release-build/installer-macOS.sh
  .github/workflows/release-build/msvc-Windows.sh
  .github/workflows/release-build/shared-library-Linux.sh
  .github/workflows/release-build/shared-library-Windows.sh
  .github/workflows/release-build/shared-library-macOS.sh
  CHANGELOG.md
  CMakeLists.txt
  appveyor.yml
  config/cmake/addlibzmq.cmake
  config/cmake/copy_key_files.cmake
  config/cmake/version_describe.cmake
  docs/ROADMAP.md
  docs/developer-guide/continuous-integration.md
  docs/docker.md
  docs/installation/helics_cmake_options.md
  docs/installation/linking.md
  docs/installation/linux.md
Labels: documentation

#919 Helics create core leaked exception
  src/helics/core/coreTypeOperations.cpp
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/shared_library/badInputTests.cpp
Labels: bug

#924 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-or-design-question.md
  .github/SUPPORT.md
Labels: ux
