Repository GMLC-TDC/HELICS, pull requests merged in 2020-04, with the labels that each got.

#1169 Add spack install to list of package managers
  README.md
  docs/installation/index.md
  docs/installation/package_manager.md
Labels: documentation

#1170 Merge master docs to develop
  README.md
  docs/installation/index.md
  docs/installation/package_manager.md
Labels: documentation

#1176 Set BOOST_ROOT to Boost 1.72.0 on Windows Azure CI
  .ci/azure-pipelines.yml
Labels: bug

#1180 Add cpplint job on GitHub Actions
  .github/workflows/static-analyzers.yml
  CPPLINT.cfg
Labels: testing

#1175 Rest api update
  docs/user-guide/index.md
  docs/user-guide/running_interaction.md
  docs/user-guide/simultaneous_cosimulations.md
  docs/user-guide/webserver.md
  src/helics/apps/CMakeLists.txt
  src/helics/apps/helicsWebServer.cpp
  src/helics/apps/helicsWebServer.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  tests/helics/CMakeLists.txt
  tests/helics/webserver/CMakeLists.txt
  tests/helics/webserver/helics_webserver_tests.cpp
  tests/helics/webserver/webServerHttpTests.cpp
  tests/helics/webserver/webServerWebSocketTests.cpp
Labels: enhancement

#1181 Json config parser
  ThirdParty/helics/external/CLI11/CLI11.hpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/apps/BrokerServer.cpp
  src/helics/core/CMakeLists.txt
  src/helics/core/helicsCLI11.hpp
  src/helics/core/helicsCLI11JsonConfig.cpp
  src/helics/core/helicsCLI11JsonConfig.hpp
  tests/helics/application_api/FederateInfoTests.cpp
Labels: Code Improvement, enhancement

#1183 Cpplint fixes
  CMakeLists.txt
  CPPLINT.cfg
  benchmarks/helics/EchoHubFederate.hpp
  benchmarks/helics/EchoLeafFederate.hpp
  benchmarks/helics/EchoMessageHubFederate.hpp
  benchmarks/helics/EchoMessageLeafFederate.hpp
  benchmarks/helics/MessageExchangeFederate.hpp
  benchmarks/helics/PholdFederate.hpp
  benchmarks/helics/RingTransmitFederate.hpp
  benchmarks/helics/RingTransmitMessageFederate.hpp
  benchmarks/helics/TimingHubFederate.hpp
  benchmarks/helics/TimingLeafFederate.hpp
  src/empty.cpp
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/Message.cpp
  src/helics/application_api/Publications.hpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/application_api/helicsTypes.cpp
  src/helics/apps/AsioBrokerServer.cpp
  src/helics/apps/PrecHelper.hpp
  src/helics/apps/helicsWebServer.cpp
  src/helics/chelics.h
  src/helics/common/configFileHelpers.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/HandleManager.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/cpp98/CPPLINT.cfg
  src/helics/cpp98/ValueFederate.hpp
  src/helics/helics98.hpp
  src/helics/network/inproc/InprocCore.h
  src/helics/network/ipc/IpcBlockingPriorityQueueImpl.cpp
  src/helics/network/test/TestCore.h
  src/helics/network/udp/UdpComms.cpp
  src/helics/network/zmq/ZmqComms.cpp
  src/helics/shared_api_library/CPPLINT.cfg
  src/helics/shared_api_library/helics.h
  tests/CPPLINT.cfg
  tests/helics/application_api/FederateTests.cpp
  tests/helics/shared_library/cpptestFixtures.hpp
  tests/helics/shared_library/ctestFixtures.hpp
Labels: Code Improvement

#1188 Cpplint additional
  .clang-tidy
  .github/workflows/static-analyzers.yml
  CPPLINT.cfg
  src/helics/application_api/Subscriptions.cpp
  src/helics/core/coreTypeOperations.cpp
  src/helics/core/federate_id.cpp
  src/helics/core/flagOperations.hpp
  src/helics/core/helicsCLI11.hpp
  src/helics/network/inproc/InprocBroker.cpp
  src/helics/network/ipc/IpcBlockingPriorityQueue.cpp
  src/helics/network/tcp/TcpComms.cpp
  src/helics/network/tcp/TcpComms.h
  src/helics/network/tcp/TcpCommsCommon.cpp
  src/helics/network/tcp/TcpCommsCommon.h
  src/helics/network/tcp/TcpCommsSS.cpp
  src/helics/network/tcp/TcpCommsSS.h
  tests/.clang-tidy
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/core/ForwardingTimeCoordinatorTests.cpp
  tests/helics/core/InfoClass-tests.cpp
  tests/helics/core/TimeCoordinatorTests.cpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/system_tests/ErrorTests.cpp
Labels: Code Improvement

#1202 Cpplint namespace
  CPPLINT.cfg
  benchmarks/helics/ActionMessageBenchmarks.cpp
  benchmarks/helics/BenchmarkFederate.hpp
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/EchoHubFederate.hpp
  benchmarks/helics/EchoLeafFederate.hpp
  benchmarks/helics/PholdFederate.hpp
  benchmarks/helics/RingTransmitFederate.hpp
  benchmarks/helics/RingTransmitMessageFederate.hpp
  benchmarks/helics/TimingHubFederate.hpp
  benchmarks/helics/TimingLeafFederate.hpp
  benchmarks/helics/conversionBenchmarks.cpp
  benchmarks/helics/echoBenchmarks.cpp
  benchmarks/helics/echoMessageBenchmarks.cpp
  benchmarks/helics/filterBenchmarks.cpp
  benchmarks/helics/messageLookupBenchmarks.cpp
  benchmarks/helics/messageSendBenchmarks.cpp
  benchmarks/helics/pholdBenchmarks.cpp
  benchmarks/helics/ringBenchmarks.cpp
  benchmarks/helics/ringMessageBenchmarks.cpp
  benchmarks/helics/timingBenchmarks.cpp
  config/cmake/compiler_flags.cmake
  examples/BrokerServerTestCase/brokerServerTest.cpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/helicsTypes.cpp
  src/helics/apps/MultiBroker.cpp
  src/helics/apps/Player.cpp
  src/helics/apps/PrecHelper.cpp
  src/helics/apps/Recorder.cpp
  src/helics/apps/Source.cpp
  src/helics/apps/Tracer.cpp
  src/helics/apps/helicsApp.cpp
  src/helics/apps/helicsConfigMain.cpp
  src/helics/common/zmqHelper.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/network/NetworkBrokerData.cpp
  src/helics/network/inproc/InprocComms.cpp
  src/helics/network/ipc/IpcBlockingPriorityQueueImpl.cpp
  src/helics/network/tcp/TcpCommsCommon.cpp
  src/helics/network/tcp/TcpHelperClasses.cpp
  src/helics/network/test/TestComms.cpp
  src/helics/network/zmq/ZmqComms.cpp
  src/helics/network/zmq/ZmqCommsCommon.cpp
  src/helics/network/zmq/ZmqCommsSS.cpp
  src/helics/shared_api_library/helicsExport.cpp
  tests/CPPLINT.cfg
Labels: Code Improvement

#1207 Network data config
  ThirdParty/helics/external/CLI11/CLI11.hpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/helicsCLI11JsonConfig.cpp
  src/helics/core/helicsCLI11JsonConfig.hpp
  src/helics/network/CommsInterface.hpp
  src/helics/network/NetworkBrokerData.cpp
  src/helics/network/NetworkBrokerData.hpp
  src/helics/network/NetworkBroker_impl.hpp
  src/helics/network/NetworkCore_impl.hpp
  tests/helics/application_api/CMakeLists.txt
  tests/helics/core/CMakeLists.txt
  tests/helics/core/CoreConfigureTests.cpp
  tests/helics/core/CoreFactory-tests.cpp
  tests/helics/test_files/core_config/core_config1.json
  tests/helics/test_files/core_config/core_config2.json
  tests/helics/test_files/core_config/core_config3.json
Labels: enhancement

#1216 Release build workflow updates
  .github/actions/linux-release-builder/Dockerfile
  .github/actions/linux-release-builder/entrypoint.sh
  .github/workflows/release-build/installer-Windows.sh
  .github/workflows/release-build/msvc-Windows.sh
  .github/workflows/release-build/shared-library-Windows.sh
Labels: bug

#1214 missing C++98 functions
  src/helics/cpp98/Endpoint.hpp
  src/helics/cpp98/Filter.hpp
  src/helics/cpp98/Input.hpp
  src/helics/cpp98/Publication.hpp
  src/helics/cpp98/helics.hpp
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/MessageFilters.h
  src/helics/shared_api_library/MessageFiltersExport.cpp
  src/helics/shared_api_library/ValueFederate.h
  src/helics/shared_api_library/ValueFederateExport.cpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/evilInputTests.cpp
  tests/helics/shared_library/test-message-federate.cpp
  tests/helics/shared_library/test-value-federate1.cpp
Labels: Interfaces

#1221 build configurations
  CMakeLists.txt
  docs/installation/helics_cmake_options.md
  docs/installation/linux.md
Labels: Installation/build

#1225 Fix some residual warnings from the different compilers.
  src/helics/apps/BrokerServer.cpp
  src/helics/apps/BrokerServer.hpp
  src/helics/core/MessageTimer.hpp
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/ValueFederate.h
  tests/helics/application_api/FederateInfoTests.cpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/system_tests/ErrorTests.cpp
Labels: Code Improvement

#1230 Add info on Windows dependency issues to install docs
  README.md
  docs/installation/index.md
  docs/installation/linking.md
  docs/installation/package_manager.md
Labels: documentation

#1231 Multi broker stage2
  ThirdParty/helics/external/CLI11/CLI11.hpp
  src/helics/application_api/BrokerApp.cpp
  src/helics/application_api/CombinationFederate.hpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/apps/MultiBroker.cpp
  src/helics/apps/MultiBroker.hpp
  src/helics/core/BrokerFactory.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/CoreFactory.cpp
  src/helics/core/helicsCLI11JsonConfig.cpp
  src/helics/network/CommsBroker.hpp
  src/helics/network/CommsBroker_impl.hpp
  src/helics/network/CommsInterface.cpp
  src/helics/network/CommsInterface.hpp
  src/helics/network/NetworkBrokerData.cpp
  src/helics/network/zmq/ZmqComms.cpp
  tests/helics/apps/MultiBrokerTests.cpp
  tests/helics/apps/test_files/multiBroker1.json
  tests/helics/apps/test_files/multiBroker2.json
  tests/helics/apps/test_files/multiBroker3.json
  tests/helics/apps/test_files/multiBroker4.json
  tests/helics/shared_library/CMakeLists.txt
Labels: enhancement

#1233 Release 2 5 update
  CHANGELOG.md
  CMakeLists.txt
  appveyor.yml
  docs/ROADMAP.md
  docs/Tools_using_HELICS.md
  docs/user-guide/index.md
  docs/user-guide/multibroker.md
Labels: documentation

#1236 Matlab interface build refactor
  interfaces/matlab/CMakeLists.txt
  interfaces/matlab/matlabSwigGenerateOnly.cmake
Labels: Interfaces

#1235 Java interface build refactor
  CHANGELOG.md
  interfaces/java/CMakeLists.txt
  interfaces/java/javaSwigGenerateOnly.cmake
  tests/java/CMakeLists.txt
Labels: Interfaces

#1237 Update the C Api reference list
  src/docs/c_api_reference.dox
Labels: documentation

#1239 NO ZMQ test fixes with MultiBroker tests
  src/helics/apps/helics-broker.cpp
  src/helics/core/helicsCLI11.hpp
  tests/helics/apps/MultiBrokerTests.cpp
Labels: bug

#1241 Zmq isolation
  .clang-tidy
  CHANGELOG.md
  CMakeLists.txt
  ThirdParty/cppzmq/zmq.hpp
  benchmarks/helics/helics_benchmark_util.h
  config/HELICSConfig.cmake.in
  config/cmake/addBoost.cmake
  src/helics/apps/CMakeLists.txt
  src/helics/apps/zmqBrokerServer.cpp
  src/helics/apps/zmqBrokerServer.hpp
  src/helics/common/CMakeLists.txt
  src/helics/network/CMakeLists.txt
  src/helics/network/zmq/ZmqBroker.cpp
  src/helics/network/zmq/ZmqComms.cpp
  src/helics/network/zmq/ZmqCommsCommon.cpp
  src/helics/network/zmq/ZmqCommsCommon.h
  src/helics/network/zmq/ZmqCommsSS.cpp
  src/helics/network/zmq/ZmqCommsSS.h
  src/helics/network/zmq/ZmqContextManager.cpp
  src/helics/network/zmq/ZmqContextManager.h
  src/helics/network/zmq/ZmqCore.cpp
  src/helics/network/zmq/ZmqHelper.cpp
  src/helics/network/zmq/ZmqHelper.h
  src/helics/network/zmq/ZmqRequestSets.h
  src/helics/network/zmq/zmqSocketDescriptor.cpp
  src/helics/network/zmq/zmqSocketDescriptor.h
  src/helics/shared_api_library/.clang-tidy
  src/helics/shared_api_library/helicsExport.cpp
  tests/.clang-tidy
  tests/helics/network/CMakeLists.txt
  tests/helics/network/ZeromqCore-tests.cpp
  tests/helics/network/ZeromqSSCore-tests.cpp
Labels: Code Improvement

#1253 make fix for the occasional failure of the http test.
  config/cmake/addUnits.cmake
  src/helics/core/ActionMessage.cpp
  tests/helics/webserver/webServerHttpTests.cpp
Labels: bug

#1255 add build flags call
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/PholdFederate.hpp
  benchmarks/helics/helics_benchmark_util.h
  src/helics/core/helicsVersion.hpp
  src/helics/cpp98/helics.hpp
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsExport.cpp
Labels: enhancement

#1258 Try gcc10
  .circleci/config.yml
  .circleci/tsan_suppression.txt
  CMakeLists.txt
  config/cmake/compiler_flags.cmake
Labels: testing
