Repository GMLC-TDC/HELICS, pull requests merged in 2020-08, with the labels that each got.

#1508 remove the debug postfix on interface libraries(python, java, csharp)
  benchmarks/helics/echoBenchmarks_py.py
  interfaces/csharp/CMakeLists.txt
  interfaces/java/CMakeLists.txt
  interfaces/python/CMakeLists.txt
Labels: Installation/build, Interfaces, bug

#1512 Unit eq units
  src/helics/application_api/ValueFederate.cpp
  src/helics/common/JsonProcessingFunctions.cpp
  src/helics/common/TomlProcessingFunctions.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/test_files/example_value_fed.json
Labels: bug

#1513 add dumplog, and force_logging_flush flag options for the federate.
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/helics_definitions.hpp
  src/helics/helics_enums.h
  tests/helics/application_api/LoggingTests.cpp
Labels: enhancement

#1521 Complex test
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/ValueConverter_impl.hpp
  src/helics/core/helicsCLI11.hpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/shared_library/test-value-federate1.cpp
Labels: testing

#1523 add inline to cpp98
  src/helics/cpp98/Endpoint.hpp
  src/helics/cpp98/helics.hpp
Labels: bug

#1530 Update Python and Java interface tests
  tests/java/JavaHelicsApiTests.java
  tests/python/test_message_federate.py
Labels: Interfaces, testing

#1533 add some Message constructors and tests in the C++98 API
  src/helics/cpp98/Endpoint.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/cpp98/MessageFederate.hpp
  tests/helics/shared_library/test-message-federate_cpp.cpp
Labels: Interfaces

#1539 make sure to log the send_message operation through the federate logging
  src/helics/core/CommonCore.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/InputInfo.cpp
  src/helics/core/InputInfo.hpp
Labels: ux

#1535 Change default console logger
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
Labels: Code Improvement, ux

#1524 update the release docs in preparation for 2.6.0 release
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTORS.md
  appveyor.yml
  docs/ROADMAP.md
  docs/Tools_using_HELICS.md
  docs/user-guide/logging.md
Labels: documentation

#1553 Update NEW_ROUTE command in MpiComms to work with SmallBuffer
  src/helics/network/mpi/MpiComms.cpp
Labels: bug

#1557 Handle empty install prefix without an error
  CMakeLists.txt
Labels: bug
