Repository GMLC-TDC/HELICS, pull requests merged in 2020-02, with the labels that each got.

#1058 Change macOS SDK target from 10.10 to 10.9
  .github/workflows/release-build.yml
  .github/workflows/setup-macos-10.10-sdk.sh
  .github/workflows/setup-macos-10.9-sdk.sh
Labels: Installation/build

#1059 Tcp broker server
  benchmarks/helics/messageSendBenchmarks.cpp
  config/cmake/addBoost.cmake
  config/helics-config.h.in
  examples/BrokerServerTestCase/CMakeLists.txt
  examples/BrokerServerTestCase/brokerServerTest.cpp
  examples/CMakeLists.txt
  src/helics/apps/AsioBrokerServer.cpp
  src/helics/apps/AsioBrokerServer.hpp
  src/helics/apps/BrokerServer.cpp
  src/helics/apps/BrokerServer.hpp
  src/helics/apps/CMakeLists.txt
  src/helics/apps/TypedBrokerServer.cpp
  src/helics/apps/TypedBrokerServer.hpp
  src/helics/apps/helics-broker-server.cpp
  src/helics/apps/helics-broker.cpp
  src/helics/apps/helicsWebServer.cpp
  src/helics/apps/helicsWebServer.hpp
  src/helics/apps/zmqBrokerServer.cpp
  src/helics/apps/zmqBrokerServer.hpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommsInterface.cpp
  src/helics/core/NetworkBrokerData.cpp
  src/helics/core/NetworkBrokerData.hpp
  src/helics/core/NetworkCommsInterface.cpp
  src/helics/core/NetworkCommsInterface.hpp
  src/helics/core/tcp/TcpComms.cpp
  src/helics/core/udp/UdpComms.cpp
  src/helics/core/zmq/ZmqCommsSS.cpp
  src/helics/core/zmq/ZmqCommsSS.h
  src/helics/core/zmq/ZmqCore.cpp
  tests/helics/apps/BrokerServerTests.cpp
  tests/helics/core/TcpCore-tests.cpp
  tests/helics/core/UdpCore-tests.cpp
  tests/helics/core/ZeromqSSCore-tests.cpp
Labels: enhancement

#1019 Helics compatible tools
  README.md
  docs/Tools_using_HELICS.md
  docs/user-guide/index.md
  docs/user-guide/simultaneous_cosimulations.md
Labels: documentation

#1065 Include experimental webserver in *nix release installers
  .github/workflows/release-build/installer-Linux.sh
  .github/workflows/release-build/installer-Windows.sh
  .github/workflows/release-build/installer-macOS.sh
Labels: Installation/build

#1066 Update webserver docs and docker
  config/Docker/Dockerfile-HELICS-apps
  docs/CMakeLists.txt
  docs/developer-guide/continuous-integration.md
  docs/installation/helics_cmake_options.md
  docs/user-guide/index.md
  docs/user-guide/running_interaction.md
  docs/user-guide/simultaneous_cosimulations.md
  src/helics/apps/BrokerServer.cpp
  src/helics/apps/helicsWebServer.cpp
Labels: documentation

#1069 Apps docstring fixes
  docs/apps/Broker.md
  docs/apps/Recorder.md
  docs/apps/Tracer.md
  src/helics/apps/Recorder.cpp
  src/helics/apps/Tracer.cpp
  src/helics/apps/helics-broker.cpp
Labels: bug, documentation

#1070 Update mingw package and docker doc page versions to 2.4.0
  config/packaging/mingw-w64-helics/PKGBUILD
  docs/docker.md
Labels: Installation/build, documentation

#1084 Webserver defaults
  .github/workflows/release-build/installer-Linux.sh
  .github/workflows/release-build/installer-Windows.sh
  .github/workflows/release-build/installer-macOS.sh
  CHANGELOG.md
  config/Docker/Dockerfile-HELICS-apps
  docs/installation/helics_cmake_options.md
  docs/user-guide/running_interaction.md
  src/helics/apps/CMakeLists.txt
Labels: Installation/build

#1082 Federate coverage
  CHANGELOG.md
  src/helics/application_api/Federate.cpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/apps/AsioBrokerServer.cpp
  src/helics/apps/MultiBroker.cpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/BrokerFactory.cpp
  src/helics/core/BrokerFactory.hpp
  src/helics/core/CoreFactory.cpp
  src/helics/core/CoreFactory.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/core-types.hpp
  src/helics/core/coreTypeOperations.cpp
  src/helics/helics_enums.h
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/testFixtures.cpp
  tests/helics/apps/BrokerServerTests.cpp
  tests/helics/shared_library/badInputTests.cpp
  tests/helics/shared_library/evilInputTests.cpp
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/test_files/example_unusual_filters.json
  tests/helics/test_files/example_unusual_filters2.json
  tests/helics/test_files/example_unusual_filters3.json
  tests/helics/test_files/unusual_filters.toml
  tests/helics/test_files/unusual_filters2.toml
Labels: testing

#1088 Value federate coverage
  CHANGELOG.md
  src/helics/application_api/Federate.cpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/common/CMakeLists.txt
  src/helics/common/addTargets.hpp
  src/helics/common/configFileHelpers.cpp
  src/helics/common/configFileHelpers.hpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/test_files/example_value_fed_bad.toml
  tests/helics/test_files/example_value_fed_testb.json
  tests/helics/test_files/example_value_fed_testb.toml
  tests/helics/test_files/unusual_filters2.toml
Labels: testing

#1071 Remove VS2015 Windows Server 2012 CI build
  .ci/azure-pipelines.yml
  CHANGELOG.md
Labels: testing

#1093 Cmake new policy
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  interfaces/CMakeLists.txt
  interfaces/csharp/CMakeLists.txt
  interfaces/java/CMakeLists.txt
  interfaces/java/addLoadLibraryCommand.cmake
  interfaces/java/javaSwigGenerateOnly.cmake
  interfaces/java/overwriteJavaFiles.cmake
  interfaces/matlab/generateMEXcreationScript.cmake
  interfaces/matlab/matlabSwigGenerateOnly.cmake
  interfaces/matlab/overwriteMatlabFiles.cmake
  interfaces/octave/README.md
  interfaces/octave/generateOCTcreationScript.cmake
  interfaces/octave/modifyOctSourceFile.cmake
  interfaces/python/CMakeLists.txt
  src/CMakeLists.txt
  src/helics/CMakeLists.txt
  src/helics/common/configFileHelpers.cpp
  tests/CMakeLists.txt
  tests/java/CMakeLists.txt
  tests/java/HelloWorld.java
Labels: Installation/build, Interfaces

#1091 Add multinode support to benchmark federates using a common base federate
  CHANGELOG.md
  benchmarks/helics/BenchmarkFederate.hpp
  benchmarks/helics/BenchmarkMain.cpp
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/EchoHubFederate.hpp
  benchmarks/helics/EchoLeafFederate.hpp
  benchmarks/helics/EchoMessage.hpp
  benchmarks/helics/EchoMessageHubFederate.hpp
  benchmarks/helics/EchoMessageLeafFederate.hpp
  benchmarks/helics/MessageExchangeFederate.hpp
  benchmarks/helics/PholdFederate.hpp
  benchmarks/helics/PholdFederateMain.cpp
  benchmarks/helics/RingTransmitFederate.hpp
  benchmarks/helics/RingTransmitMessageFederate.hpp
  benchmarks/helics/TimingHubFederate.hpp
  benchmarks/helics/TimingLeafFederate.hpp
  benchmarks/helics/echoBenchmarks.cpp
  benchmarks/helics/echoMessageBenchmarks.cpp
  benchmarks/helics/filterBenchmarks.cpp
  benchmarks/helics/helics_benchmark_util.h
  benchmarks/helics/messageSendBenchmarks.cpp
  benchmarks/helics/pholdBenchmarks.cpp
  benchmarks/helics/ringBenchmarks.cpp
  benchmarks/helics/ringMessageBenchmarks.cpp
  benchmarks/helics/timingBenchmarks.cpp
Labels: performance/scalability

#1097 Always set HELICS_ENABLE_SWIG when building an interface requiring swig
  interfaces/CMakeLists.txt
Labels: bug

#1102 Msys2 install instructions
  CHANGELOG.md
  config/packaging/mingw-w64-helics/PKGBUILD
  docs/installation/windows.md
Labels: documentation
