Repository GMLC-TDC/HELICS, pull requests merged in 2020-06, with the labels that each got.

#1393 Add uuid support in the webserver
  .circleci/tsan_suppression.txt
  docs/user-guide/queries.md
  src/helics/apps/helicsWebServer.cpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CoreBroker.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/webserver/webServerHttpTests.cpp
  tests/helics/webserver/webServerWebSocketTests.cpp
Labels: ux

#1396 Add HELICS 2 to 3 porting guide
  docs/developer-guide/index.md
  docs/developer-guide/porting-2-to-3.md
Labels: documentation

#1390 Docs and config
  docs/configuration/FederateFlags.md
  docs/user-guide/index.md
  docs/user-guide/multiSourceInputs.md
  src/helics/application_api/Federate.cpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/application_api/Inputs.cpp
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/MessageFederate.cpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/common/CMakeLists.txt
  src/helics/common/addTargets.cpp
  src/helics/common/addTargets.hpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/InterfaceInfo.cpp
  src/helics/helics_enums.h
  tests/helics/application_api/MultiInputTests.cpp
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/test_files/multi_input_config.json
  tests/helics/test_files/multi_input_config.toml
Labels: documentation

#1402 add some more config tests to make sure the flags are working properly
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/common/addTargets.cpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/helics.h
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/test_files/bes_config.json
  tests/helics/test_files/bes_config.toml
  tests/helics/test_files/bes_config2.json
  tests/helics/test_files/bes_config2.toml
Labels: Code Improvement, bug

#1417 Add print_systeminfo flag to root helics_benchmark command
  benchmarks/helics/BenchmarkMain.cpp
Labels: testing

#1414 add cppcheck static analyzer
  .github/workflows/static-analyzers.yml
  config/cppcheck_suppressions.txt
  src/helics/application_api/helicsTypes.hpp
  src/helics/core/core-exceptions.hpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/MessageFiltersExport.cpp
  src/helics/shared_api_library/ValueFederateExport.cpp
  tests/helics/shared_library/FilterTests_cpp.cpp
  tests/helics/shared_library/ValueConverterTests.cpp
Labels: Code Improvement, testing

#1399 Add CI infrastructure plan doc
  docs/developer-guide/ci-cd-infrastructure.md
  docs/developer-guide/index.md
Labels: documentation

#1419 Allow setting Python build output folders when not run as a HELICS subproject
  CMakeLists.txt
  interfaces/python/CMakeLists.txt
Labels: Interfaces, bug

#1433 Global time block
  src/helics/application_api/BrokerApp.cpp
  src/helics/application_api/BrokerApp.hpp
  src/helics/apps/helicsWebServer.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/Broker.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/flagOperations.hpp
  src/helics/cpp98/Broker.hpp
  src/helics/network/tcp/TcpComms.cpp
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/timingTests_cpp.cpp
  tests/helics/system_tests/TimingTests2.cpp
  tests/helics/webserver/webServerHttpTests.cpp
  tests/helics/webserver/webServerWebSocketTests.cpp
Labels: enhancement

#1443 add some docs for the time barrier operations
  docs/user-guide/debugging.md
  docs/user-guide/index.md
  docs/user-guide/webserver.md
Labels: documentation
