Repository GMLC-TDC/HELICS, pull requests merged in 2020-03, with the labels that each got.

#1105 Add FreeBSD CI build
  .cirrus.yml
  CHANGELOG.md
  CMakeLists.txt
  docs/developer-guide/continuous-integration.md
Labels: testing

#1106 update the instructions for MSYS2 installation to include the pip ins…
  docs/installation/windows.md
Labels: documentation

#1108 Warning fixes
  CMakeLists.txt
  appveyor.yml
  benchmarks/helics/PholdFederate.hpp
  docs/ROADMAP.md
  docs/installation/helics_cmake_options.md
  src/helics/apps/Clone.hpp
  src/helics/apps/helicsWebServer.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.hpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/SystemTests.cpp
  tests/helics/shared_library/test-message-federate.cpp
Labels: Code Improvement, Installation/build

#1112 Send helics-version-update event to helics-packaging after new releases
  .github/workflows/release-build.yml
  CHANGELOG.md
Labels: Installation/build, Interfaces

#1113 Add win32 release zip archive
  .github/workflows/release-build.yml
  CHANGELOG.md
Labels: Installation/build

#1116 Windows installer clean-up
  CHANGELOG.md
  CMakeLists.txt
Labels: Installation/build, ux

#1125 Update generated HELICS apps manpages
  CHANGELOG.md
  docs/man/manpage_out/helics_app-broker.1
  docs/man/manpage_out/helics_app-clone.1
  docs/man/manpage_out/helics_app-echo.1
  docs/man/manpage_out/helics_app-player.1
  docs/man/manpage_out/helics_app-recorder.1
  docs/man/manpage_out/helics_app-source.1
  docs/man/manpage_out/helics_app-tracer.1
  docs/man/manpage_out/helics_app.1
  docs/man/manpage_out/helics_broker-term.1
  docs/man/manpage_out/helics_broker.1
  docs/man/manpage_out/helics_player.1
Labels: documentation

#1127 Add pip to install docs
  docs/developer-guide/swig.md
  docs/installation/index.md
  docs/installation/package_manager.md
  docs/introduction/python.md
Labels: documentation

#1126 Final Version and doc update to roadmap and readme and date.
  CMakeLists.txt
  README.md
  docs/ROADMAP.md
Labels: documentation

#1121 New queries
  CHANGELOG.md
  docs/user-guide/queries.md
  src/helics/application_api/Federate.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/ForwardingTimeCoordinator.cpp
  src/helics/core/ForwardingTimeCoordinator.hpp
  src/helics/core/TimeCoordinator.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: enhancement

#1130 Fix macOS Python interface build
  interfaces/python/CMakeLists.txt
Labels: bug

#1135 Mfed tests
  CHANGELOG.md
  src/helics/application_api/CombinationFederate.hpp
  src/helics/application_api/MessageFederate.cpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/core/FederateState.cpp
  tests/helics/application_api/CombinationFederateTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/test_files/example_message_fed_bad.toml
  tests/helics/test_files/example_message_fed_testb.json
Labels: testing

#1137 Fix link in user guide
  docs/user-guide/index.md
Labels: bug, documentation

#1145 Fix the timing benchmark federate names
  benchmarks/helics/TimingHubFederate.hpp
  benchmarks/helics/TimingLeafFederate.hpp
Labels: bug

#1148 change CSharp interface module name to be helics instead of csharp
  interfaces/csharp/CMakeLists.txt
Labels: Interfaces, bug

#1149 Test zmq disable
  .circleci/config.yml
  CHANGELOG.md
  CMakeLists.txt
  config/cmake/compiler_flags.cmake
  config/helics-config.h.in
  src/helics/apps/AsioBrokerServer.cpp
  src/helics/apps/AsioBrokerServer.hpp
  src/helics/apps/BrokerServer.cpp
  src/helics/apps/CMakeLists.txt
  src/helics/apps/MultiBroker.cpp
  src/helics/apps/zmqBrokerServer.cpp
  src/helics/apps/zmqBrokerServer.hpp
  src/helics/core/BrokerBase.cpp
  tests/helics/apps/BrokerServerTests.cpp
  tests/helics/shared_library/comboConfigTests.cpp
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/system_tests/TimingTests.cpp
  tests/helics/system_tests/brokerTimeoutTests.cpp
Labels: Installation/build, bug, testing

#1152 Core app tests
  .codecov.yml
  src/helics/application_api/BrokerApp.cpp
  src/helics/application_api/BrokerApp.hpp
  src/helics/application_api/CoreApp.cpp
  src/helics/application_api/CoreApp.hpp
  src/helics/application_api/Federate.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreFactory.cpp
  src/helics/cxx_shared_library/CoreFactory.hpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/apps/CMakeLists.txt
  tests/helics/apps/CoreAppTests.cpp
Labels: testing

#1143 Test fails
  docs/configuration/MessageFederate.md
  docs/configuration/ValueFederate.md
  examples/example_files/example_combo_fed.json
  examples/example_files/example_combo_fed.toml
  examples/example_files/example_filters.json
  examples/example_files/example_filters.toml
  examples/example_files/example_message_fed.json
  examples/example_files/example_message_fed.toml
  examples/example_files/example_value_fed.json
  examples/example_files/example_value_fed.toml
  src/helics/application_api/FederateInfo.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/NetworkBrokerData.cpp
  src/helics/core/federate_id.hpp
  src/helics/core/global_federate_id.hpp
  tests/helics/core/BrokerClassTests.cpp
  tests/helics/core/MessageTimerTests.cpp
  tests/helics/core/networkInfoTests.cpp
  tests/helics/shared_library/SystemTests.cpp
  tests/helics/test_files/example_combo_fed.json
  tests/helics/test_files/example_combo_fed.toml
  tests/helics/test_files/example_filters.json
  tests/helics/test_files/example_filters.toml
  tests/helics/test_files/example_message_fed.json
  tests/helics/test_files/example_message_fed.toml
  tests/helics/test_files/example_message_fed_bad.toml
  tests/helics/test_files/example_message_fed_testb.json
  tests/helics/test_files/example_unusual_filters.json
  tests/helics/test_files/example_unusual_filters2.json
  tests/helics/test_files/example_unusual_filters3.json
  tests/helics/test_files/example_value_fed.toml
  tests/helics/test_files/example_value_fed_bad.toml
  tests/helics/test_files/example_value_fed_testb.toml
  tests/helics/test_files/unusual_filters.toml
  tests/helics/test_files/unusual_filters2.toml
Labels: bug, testing

#1154 Broker app tests
  src/helics/core/CommonCore.cpp
  tests/helics/apps/BrokerAppTests.cpp
  tests/helics/apps/CMakeLists.txt
Labels: testing

#1156 Fed info tests
  src/helics/application_api/CoreApp.cpp
  src/helics/application_api/CoreApp.hpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/common/TomlProcessingFunctions.hpp
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/FederateInfoTests.cpp
  tests/helics/application_api/PrimaryTypeConversionTests.cpp
  tests/helics/application_api/federateRealTimeTests.cpp
  tests/helics/apps/BrokerServerTests.cpp
  tests/helics/apps/CoreAppTests.cpp
  tests/helics/shared_library/cpptestFixtures.hpp
  tests/helics/shared_library/test-message-federate_cpp.cpp
  tests/helics/shared_library/test-value-federate2_cpp.cpp
  tests/helics/system_tests/federateRealTimeTests.cpp
  tests/helics/test_files/example_value_fed.json
  tests/helics/test_files/example_value_fed.toml
Labels: testing

#1158 Additional type tests
  src/helics/application_api/helicsTypes.cpp
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/PrimaryTypeConversionTests.cpp
  tests/helics/application_api/helicsTypeTests.cpp
Labels: testing

#1160 Query cleanup
  src/helics/common/JsonBuilder.cpp
  src/helics/common/JsonBuilder.hpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/InterfaceInfo.cpp
  src/helics/core/InterfaceInfo.hpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  tests/helics/system_tests/QueryTests.cpp
Labels: Code Improvement, enhancement
