Repository GMLC-TDC/HELICS, pull requests merged in 2020-07, with the labels that each got.

#1438 All queries JSON
  docs/user-guide/queries.md
  src/helics/application_api/Federate.cpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/application_api/queryFunctions.cpp
  src/helics/apps/helicsWebServer.cpp
  src/helics/common/CMakeLists.txt
  src/helics/common/JsonGeneration.hpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/InputInfo.cpp
  src/helics/core/queryHelpers.hpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/common/CMakeLists.txt
  tests/helics/common/JsonGenerationTests.cpp
  tests/helics/shared_library/QueryTests.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/webserver/webServerHttpTests.cpp
Labels: ux, v3 api change

#1448 Add option to install benchmark executables
  CMakeLists.txt
  benchmarks/helics/CMakeLists.txt
Labels: Installation/build

#1435 add the frozen library and get rid of some hacky code for the actionM…
  ThirdParty/frozen/CMakeLists.txt
  ThirdParty/frozen/algorithm.h
  ThirdParty/frozen/bits/algorithms.h
  ThirdParty/frozen/bits/basic_types.h
  ThirdParty/frozen/bits/constexpr_assert.h
  ThirdParty/frozen/bits/elsa.h
  ThirdParty/frozen/bits/exceptions.h
  ThirdParty/frozen/bits/pmh.h
  ThirdParty/frozen/bits/version.h
  ThirdParty/frozen/map.h
  ThirdParty/frozen/random.h
  ThirdParty/frozen/set.h
  ThirdParty/frozen/string.h
  ThirdParty/frozen/unordered_map.h
  ThirdParty/frozen/unordered_set.h
  src/helics/core/ActionMessage.cpp
  src/helics/core/Broker.hpp
Labels: Code Improvement, v3 api change

#1459 CMake error if user sets the install prefix to the build folder
  CMakeLists.txt
Labels: Installation/build, bug

#1461 Benchmark build workflow
  .github/actions/benchmark-build/benchmark-Linux.sh
  .github/actions/benchmark-build/benchmark-Windows.sh
  .github/actions/benchmark-build/benchmark-macOS.sh
  .github/workflows/benchmark-package.yml
Labels: testing

#1457 V3userguide b
  docs/CMakeLists.txt
  docs/apps/index.md
  docs/configuration/Federate.md
  docs/configuration/FederateFlags.md
  docs/configuration/FederateInfo.md
  docs/configuration/Filters.md
  docs/configuration/InterfaceFlags.md
  docs/configuration/MessageFederate.md
  docs/configuration/Timing.md
  docs/configuration/ValueFederate.md
  docs/configuration/index.md
  docs/configuration_options_reference.md
  docs/img/broker_hierarchy_broker_topology.png
  docs/img/broker_hierarchy_message_topology.png
  docs/img/web_interface_overview.png
  docs/index.md
  docs/introduction/Endpoints.md
  docs/introduction/Inputs.md
  docs/introduction/LanguageAPIs.md
  docs/introduction/Publications.md
  docs/introduction/filters.md
  docs/introduction/hello-world.md
  docs/introduction/index.md
  docs/introduction/java.md
  docs/introduction/matlab.md
  docs/introduction/original_specification.md
  docs/introduction/pubsub-vs-message.md
  docs/introduction/python.md
  docs/introduction/terminology.md
  docs/introduction/types-of-federates.md
  docs/support.md
  docs/user-guide/CoreTypes.md
  docs/user-guide/broker_hierarchies.md
  docs/user-guide/co-simulation_overview.md
  docs/user-guide/federates.md
  docs/user-guide/filters.md
  docs/user-guide/helics_co-sim_sequence.md
  docs/user-guide/helics_key_concepts.md
  docs/user-guide/index.md
  docs/user-guide/message_federates.md
  docs/user-guide/timing.md
  docs/user-guide/troubleshooting.md
  docs/user-guide/value_federates.md
  docs/user-guide/value_types.md
  docs/user-guide/web_interface.md
  src/helics/application_api/ValueConverter.cpp
Labels: documentation

#1464 Helics3 converters
  src/helics/application_api/ValueConverter.cpp
  src/helics/application_api/ValueConverter.hpp
  tests/helics/application_api/ValueConverterTests.cpp
Labels: Code Improvement, performance/scalability

#1452 make the vector/complex number conversions to fit JSON standard.
  ThirdParty/frozen/bits/pmh.h
  ThirdParty/frozen/string.h
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/application_api/ValueFederateManager.hpp
  src/helics/application_api/helicsTypes.cpp
  src/helics/application_api/helicsTypes.hpp
  src/helics/common/JsonProcessingFunctions.cpp
  src/helics/common/JsonProcessingFunctions.hpp
  tests/helics/application_api/PrimaryTypeConversionTests.cpp
  tests/helics/application_api/helicsTypeTests.cpp
  tests/helics/shared_library/test-value-federate1.cpp
  tests/helics/system_tests/updateTests.cpp
Labels: Code Improvement

#1490 Set no_delay on TCP sockets
  src/helics/network/tcp/TcpHelperClasses.cpp
Labels: performance/scalability

#1451 Benchmark python testing
  benchmarks/helics/echoBenchmarks_py.py
Labels: Interfaces, performance/scalability

#1488 Small buffer
  src/helics/common/CMakeLists.txt
  src/helics/common/SmallBuffer.cpp
  src/helics/common/SmallBuffer.hpp
  tests/helics/common/CMakeLists.txt
  tests/helics/common/SmallBufferTests.cpp
Labels: enhancement, performance/scalability
