Repository GMLC-TDC/HELICS, pull requests merged in 2020-01, with the labels that each got.

#1000 Add an MSYS build to Travis CI
  .travis.yml
  scripts/ci-build.sh
  scripts/run-ci-tests.sh
  scripts/run-core-ci-tests.sh
  scripts/sanitizer_tests.sh
Labels: testing

#1006 Java msys
  interfaces/java/CMakeLists.txt
  interfaces/java/MakeJarCMakeLists.txt.in
Labels: Interfaces, bug

#985 Adds a CMake function to Git Submodules logic to check if all submodules are current
  CMakeLists.txt
  config/cmake/updateGitSubmodules.cmake
  docs/installation/helics_cmake_options.md
Labels: Installation/build

#1011 add c shared lib benchmark
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/echoBenchmarks_c.cpp
  benchmarks/helics/helics_benchmark_main.h
Labels: performance/scalability

#1012 Multinode PHOLD benchmark
  benchmarks/helics/CMakeLists.txt
  benchmarks/helics/PholdFederate.hpp
  benchmarks/helics/PholdFederateMain.cpp
  benchmarks/helics/helics_benchmark_main.h
  benchmarks/helics/helics_benchmark_util.h
  benchmarks/helics/multinode/phold-sbatch-submitter.sh
  benchmarks/helics/multinode/phold.sbatch
  docs/developer-guide/benchmarks.md
Labels: performance/scalability

#1009 make a few minor tweaks to the build to make the configuration work w…
  CMakeLists.txt
  config/cmake/addZeroMQ.cmake
  config/cmake/addlibzmq.cmake
  config/packaging/mingw-w64-helics/PKGBUILD
  docs/installation/helics_cmake_options.md
Labels: Installation/build

#1008 Add .git directory detection to fix fatal error
  config/cmake/addGitHooks.cmake
Labels: bug

#1014 Set HELICS_SWIG_INCLUDE_DIRS variable for standalone interface builds
  CMakeLists.txt
  config/HELICSConfig.cmake.in
  interfaces/CMakeLists.txt
  interfaces/output.i
Labels: Interfaces

#1020 Add support for standalone Python3 interface builds
  CMakeLists.txt
  config/HELICSConfig.cmake.in
  interfaces/CMakeLists.txt
  interfaces/python/CMakeLists.txt
  interfaces/python/addHelicsPy3Lib.cmake
  interfaces/python/helicsPython.i
  interfaces/python/pythonSwigGenerateOnly.cmake
Labels: Interfaces

#1023 Remove dependency on Python for generating the swig interface
  docs/installation/language.md
  interfaces/python/CMakeLists.txt
  interfaces/python/pythonSwigGenerateOnly.cmake
Labels: Interfaces, documentation

#1026 fix an issue with the dependencies on the benchmark builds and put th…
  benchmarks/helics/CMakeLists.txt
  src/helics/cpp98/ValueFederate.hpp
Labels: performance/scalability

#1029 Make sure the python module can find a copy of helicsSharedLib
  interfaces/python/CMakeLists.txt
Labels: Installation/build, Interfaces

#1024 Shared lib coverage
  .circleci/config.yml
  .circleci/ubsan_suppression.txt
  .codecov.yml
  benchmarks/helics/PholdFederateMain.cpp
  benchmarks/helics/echoBenchmarks_c.cpp
  src/helics/application_api/FilterOperations.cpp
  src/helics/application_api/FilterOperations.hpp
  src/helics/application_api/Filters.cpp
  src/helics/application_api/Filters.hpp
  src/helics/application_api/Inputs.cpp
  src/helics/application_api/Inputs.hpp
  src/helics/application_api/MessageOperators.cpp
  src/helics/application_api/MessageOperators.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/core-data.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/MessageFiltersExport.cpp
  src/helics/shared_api_library/ValueFederateExport.cpp
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/QueryTests.cpp
  tests/helics/shared_library/SystemTests.cpp
  tests/helics/shared_library/TimingTests.cpp
  tests/helics/shared_library/badInputTests.cpp
  tests/helics/shared_library/evilInputTests.cpp
  tests/helics/shared_library/loggingTests.cpp
  tests/helics/shared_library/test-message-federate.cpp
  tests/helics/shared_library/test-value-federate1.cpp
Labels: testing

#1035 Add STATUS mode to all cmake message() calls
  config/cmake/GitUtils.cmake
  config/cmake/ucm.cmake
  interfaces/python/CMakeLists.txt
Labels: Interfaces, bug

#1036 Set macOS rpaths to make installs movable
  CMakeLists.txt
  interfaces/python/CMakeLists.txt
Labels: Installation/build

#1037 Disable automated formatting for PRs from forks
  .github/workflows/clang-format.yml
Labels: bug

#1038 Slimmer all source release tarball
  scripts/_git-all-archive.sh
Labels: Installation/build

#1041 Add a Linux installer to the release builds
  .github/workflows/release-build.yml
  .github/workflows/release-build/installer-Linux.sh
Labels: Installation/build

#1051 Static link the ZeroMQ library for Windows release builds
  .github/workflows/release-build/installer-Windows.sh
  .github/workflows/release-build/shared-library-Windows.sh
  README.md
Labels: Installation/build

#1052 Add man pages for HELICS executables
  CMakeLists.txt
  docs/man/apps-common-options.adoc
  docs/man/broker-options.adoc
  docs/man/federate-apps-common-options.adoc
  docs/man/federate-info-options.adoc
  docs/man/generate_manpages.sh
  docs/man/helics_app-broker.adoc
  docs/man/helics_app-clone.adoc
  docs/man/helics_app-echo.adoc
  docs/man/helics_app-player.adoc
  docs/man/helics_app-recorder.adoc
  docs/man/helics_app-source.adoc
  docs/man/helics_app-tracer.adoc
  docs/man/helics_app.adoc
  docs/man/helics_broker-term.adoc
  docs/man/helics_broker.adoc
  docs/man/helics_player.adoc
  docs/man/helics_recorder.adoc
  docs/man/logging-options.adoc
  docs/man/logging-synopsis.adoc
  docs/man/manpage_out/helics_app-broker.1
  docs/man/manpage_out/helics_app-clone.1
  docs/man/manpage_out/helics_app-echo.1
  docs/man/manpage_out/helics_app-player.1
  docs/man/manpage_out/helics_app-recorder.1
  docs/man/manpage_out/helics_app-source.1
  docs/man/manpage_out/helics_app-tracer.1
  docs/man/manpage_out/helics_app.1
  docs/man/manpage_out/helics_broker-term.1
  docs/man/manpage_out/helics_broker.1
  docs/man/manpage_out/helics_player.1
  docs/man/player-contents.adoc
  docs/man/recorder-contents.adoc
  docs/man/timeout-options.adoc
  docs/man/timeout-synopsis.adoc
Labels: documentation

#1054 Get Python extension suffix and fix several minor issues
  interfaces/python/CMakeLists.txt
  interfaces/python/addHelicsPy3Lib.cmake
  interfaces/python/pythonSwigGenerateOnly.cmake
Labels: Interfaces

#1056 Fix CONTRIBUTORS.md link to gulrak/filesystem
  CONTRIBUTORS.md
Labels: bug, documentation

#1055 Filter CI tests run on Travis
  .travis.yml
  scripts/run-ci-tests.sh
  scripts/run-core-ci-tests.sh
  scripts/setup-helics-ci-options.sh
Labels: testing
