Repository GMLC-TDC/HELICS, pull requests merged in 2020-10, with the labels that each got.

#1614 Global state query
  docs/user-guide/queries.md
  src/helics/common/JsonBuilder.cpp
  src/helics/common/JsonBuilder.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  tests/helics/system_tests/QueryTests.cpp
Labels: Code Improvement, enhancement

#1619 add a requested time field to the current_time query result
  docs/user-guide/queries.md
  src/helics/core/CommonCore.cpp
  src/helics/core/TimeCoordinator.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: bug

#1627 Add workflow_dispatch trigger to test releases
  .github/workflows/release-build.yml
Labels: Installation/build

#1629 Make some changes to support boost 1.74 to the webserver
  config/cmake/addBoost.cmake
  src/helics/apps/CMakeLists.txt
  src/helics/apps/helicsWebServer.cpp
Labels: Installation/build

#1622 add a message clear operation for Message to the C++/C/C++98 APi's
  src/helics/core/core-data.hpp
  src/helics/cpp98/Endpoint.hpp
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/MessageFederateExport.cpp
  tests/helics/shared_library/test-message-federate.cpp
Labels: enhancement

#1632 Test out cmake 3.18
  CMakeLists.txt
  appveyor.yml
  benchmarks/CMakeLists.txt
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Installation/build

#1642 Issue #1548
  .gitattributes
  docs/introduction/hello-world-VS.md
  docs/introduction/hello-world.md
  src/helics/application_api/FederateInfo.cpp
  src/helics/network/tcp/TcpHelperClasses.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/PropertyIndexTests.cpp
Labels: bug

#1634 C api query callback
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/cpp98/Federate.hpp
  src/helics/cpp98/config.hpp
  src/helics/shared_api_library/api-data.h
  src/helics/shared_api_library/helicsCallbacks.cpp
  src/helics/shared_api_library/helicsCallbacks.h
  tests/helics/shared_library/QueryTests.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: enhancement

#1639 Add handling for duplicate target specification
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/InputInfo.cpp
  src/helics/core/InputInfo.hpp
  src/helics/core/PublicationInfo.cpp
  src/helics/core/PublicationInfo.hpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/test_files/fed1_config.json
  tests/helics/test_files/fed2_config.json
Labels: bug

#1648 Broker port tests
  src/helics/network/NetworkBrokerData.cpp
  src/helics/network/NetworkCommsInterface.cpp
  tests/helics/system_tests/networkTests.cpp
Labels: bug

#1645 add indexing tests and missing ones for the flag enumerations
  src/helics/application_api/FederateInfo.cpp
  src/helics/helics_enums.h
  src/helics/network/tcp/TcpHelperClasses.cpp
  tests/helics/application_api/FederateInfoTests.cpp
  tests/helics/shared_library/PropertyIndexTests.cpp
Labels: bug

#1659 add debugging flag
  docs/configuration/FederateFlags.md
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/helics_definitions.hpp
  src/helics/helics_enums.h
  tests/helics/system_tests/brokerTimeoutTests.cpp
Labels: enhancement

#1668 Octave build
  .circleci/config.yml
  config/cmake/copy_key_files.cmake
  interfaces/octave/octave_maps.i
  tests/octave/messageFedTests.m
  tests/octave/messageFilterTests.m
  tests/octave/runTestsCIRCLECI.m
  tests/octave/valueFedTests.m
Labels: Installation/build, Interfaces, testing
