Repository GMLC-TDC/HELICS, pull requests merged in 2021-08, with the labels that each got.

#2043 Json serialization
  CMakeLists.txt
  README.md
  benchmarks/helics/ActionMessageBenchmarks.cpp
  src/helics/application_api/BrokerApp.hpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/GlobalFederateId.hpp
  src/helics/core/flagOperations.hpp
  src/helics/network/CommsInterface.hpp
  src/helics/network/NetworkBrokerData.cpp
  src/helics/network/NetworkBrokerData.hpp
  src/helics/network/NetworkBroker_impl.hpp
  src/helics/network/NetworkCommsInterface.cpp
  src/helics/network/NetworkCore_impl.hpp
  src/helics/network/zmq/ZmqComms.cpp
  src/helics/shared_api_library/backup/helics/helics.h
  src/helics/shared_api_library/backup/helics/helics_api.h
  tests/helics/application_api/FederateTests.cpp
  tests/helics/core/ActionMessage-tests.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: enhancement

#2041 Fix doxygen read the docs build
  docs/references/api-reference/index.md
  scripts/render-doxyfile.py
Labels: bug, documentation

#2045 Run pre-commit clang-format on generated interface files
  .github/workflows/swig-interface-gen.yml
Labels: bug, infrastructure/ci

#2028 Upgrade pre-commit hooks and skip clang-format on pre-commit.ci
  .github/workflows/formatting.yml
  .pre-commit-config.yaml
Labels: infrastructure/ci

#2058 Add workflow_dispatch trigger to formatting and static analyzer workflows
  .github/workflows/formatting.yml
  .github/workflows/static-analyzers.yml
Labels: infrastructure/ci
