Repository GMLC-TDC/HELICS, pull requests merged in 2021-05, with the labels that each got.

#1889 Fix compress images workflow condition
  .github/workflows/compress-images.yml
Labels: infrastructure/ci

#1882 Interface tags
  src/helics/application_api/Endpoints.cpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/MessageFederate.cpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/common/TomlProcessingFunctions.hpp
  src/helics/common/addTargets.cpp
  src/helics/common/addTargets.hpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/BasicHandleInfo.cpp
  src/helics/core/BasicHandleInfo.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/queryHelpers.cpp
  src/helics/core/queryHelpers.hpp
  src/helics/cpp98/Filter.hpp
  src/helics/cpp98/Input.hpp
  src/helics/cpp98/Publication.hpp
  src/helics/helics_enums.h
  src/helics/network/tcp/TcpHelperClasses.cpp
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/MessageFilters.h
  src/helics/shared_api_library/MessageFiltersExport.cpp
  src/helics/shared_api_library/ValueFederate.h
  src/helics/shared_api_library/ValueFederateExport.cpp
  src/helics/shared_api_library/backup/helics.h
  src/helics/shared_api_library/backup/helics_api.h
  tests/helics/application_api/FederateInfoTests.cpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/apps/CloneTests.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/shared_library/miscApiTests.cpp
  tests/helics/shared_library/test-message-federate.cpp
  tests/helics/shared_library/test-value-federate1.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/system_tests/TimingTests.cpp
  tests/helics/test_files/example_value_fed_testb.json
  tests/helics/test_files/example_value_fed_testb.toml
Labels: enhancement

#1903 Disable Java interface for code coverage builds
  .github/workflows/code-coverage.yml
Labels: infrastructure/ci

#1919 Core naming fix
  src/helics/application_api/Federate.cpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/core/CMakeLists.txt
  tests/helics/core/CoreOperationsTests.cpp
  tests/helics/test_files/name_config1.json
  tests/helics/test_files/name_config2.json
Labels: bug

#1921 Environmental variables
  docs/user-guide/debugging.md
  docs/user-guide/environment_variables.md
  docs/user-guide/index.md
  docs/user-guide/queries.md
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/FederateInfo.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/helicsCLI11.hpp
  src/helics/network/CommsInterface.cpp
  src/helics/network/CommsInterface.hpp
  src/helics/network/NetworkBrokerData.cpp
  src/helics/network/NetworkBrokerData.hpp
  src/helics/network/NetworkCommsInterface.cpp
  src/helics/network/NetworkCore_impl.hpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/testFixtures.cpp
  tests/helics/application_api/testFixtures.hpp
  tests/helics/system_tests/networkTests.cpp
Labels: enhancement
