Repository GMLC-TDC/HELICS, pull requests merged in 2021-04, with the labels that each got.

#1819 Switch HELICS 2 develop branch CI from Travis to Azure Pipelines
  .ci/azure-pipelines.yml
  .travis.yml
  scripts/setup-helics-ci-options.sh
Labels: infrastructure/ci

#1825 Broker server tests
  src/helics/application_api/ValueFederate.cpp
  src/helics/apps/helics-broker-server.cpp
  src/helics/apps/helicsWebServer.cpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/BrokerFactory.cpp
  src/helics/core/BrokerFactory.hpp
  tests/helics/system_tests/networkTests.cpp
  tests/helics/webserver/webServerHttpTests.cpp
  tests/helics/webserver/webServerWebSocketTests.cpp
Labels: bug

#1828 Update HELICS 2 FreeBSD CI build to 12.2
  .cirrus.yml
Labels: infrastructure/ci

#1835 Add vcpkg manifest file
  CMakeLists.txt
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
  vcpkg.json
Labels: Installation/build

#1841 Add support for finding MSVC ZMQ library versions 4.3.3 and 4.3.4
  config/cmake/FindZeroMQ.cmake
Labels: Installation/build

#1845 Default HELICS_USE_ZMQ_STATIC_LIBRARY=ON if only the static zmq library is found
  config/cmake/addZeroMQ.cmake
  docs/installation/helics_cmake_options.md
Labels: Installation/build

#1859 Add swigwin-4.0.2 to list of search paths
  interfaces/CMakeLists.txt
Labels: Installation/build

#1864 Fix docs markdown linting errors
  docs/references/configuration_options_reference.md
  docs/user-guide/advanced_topics/orchestration.md
  docs/user-guide/advanced_topics/orchestration_monte_carlo.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_hierarchies.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_multibroker.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_simultaneous.md
  docs/user-guide/examples/advanced_examples/advanced_default.md
  docs/user-guide/examples/advanced_examples/advanced_examples_index.md
  docs/user-guide/examples/advanced_examples/advanced_query.md
  docs/user-guide/examples/fundamental_examples/fundamental_combo.md
  docs/user-guide/examples/fundamental_examples/fundamental_default.md
  docs/user-guide/examples/fundamental_examples/fundamental_endpoints.md
  docs/user-guide/examples/fundamental_examples/fundamental_examples_index.md
  docs/user-guide/examples/fundamental_examples/fundamental_fedintegration.md
  docs/user-guide/fundamental_topics/helics_cli.md
  docs/user-guide/fundamental_topics/interface_configuration.md
  docs/user-guide/fundamental_topics/logging.md
  docs/user-guide/fundamental_topics/simulator_integration.md
  docs/user-guide/support.md
Labels: bug, documentation

#1830 Add logging, player, + recorder to debug note in User Guide
  docs/user-guide/debugging.md
Labels: documentation
