Repository GMLC-TDC/HELICS, pull requests merged in 2021-11, with the labels that each got.

#2143 Update CI build to clang13-builder
  .ci/azure-pipelines.yml
Labels: infrastructure/ci

#2160 Give an error for attempted Python interface builds
  interfaces/CMakeLists.txt
Labels: Interfaces, Installation/build

#2144 Fix for linkers that don't support --version-script
  docs/developer-guide/porting-2-to-3.md
  docs/user-guide/installation/build_from_source.md
  docs/user-guide/installation/helics_cmake_options.md
  docs/user-guide/installation/linux.md
  docs/user-guide/installation/mac.md
  docs/user-guide/installation/windows.md
  src/helics/shared_api_library/CMakeLists.txt
Labels: bug, Installation/build

#2174 Backport Boost 1.77 fix to HELICS 2
  config/cmake/addBoost.cmake
  src/helics/network/ipc/IpcQueueHelper.cpp
Labels: bug

#2190 Fix formatting in the generated helics header files
  .github/workflows/swig-interface-gen.yml
  scripts/generateHelicsH.py
  src/helics/shared_api_library/backup/helics/helics_api.h
Labels: bug

#2199 Remove helics::zmq target dependency when ZMQ core is disabled
  src/helics/network/CMakeLists.txt
Labels: bug

#2204 pre-commit.ci: autoupdate the develop branch
  .pre-commit-config.yaml
Labels: infrastructure/ci

#2198 Grant timeout
  appveyor.yml
  docs/references/configuration_options_reference.md
  src/helics/application_api/Federate.cpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreFactory.cpp
  src/helics/core/CoreFactory.hpp
  src/helics/core/CoreTypes.hpp
  src/helics/core/EmptyCore.cpp
  src/helics/core/EmptyCore.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/MessageTimer.cpp
  src/helics/core/MessageTimer.hpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/core-exceptions.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/helics_enums.h
  tests/helics/application_api/CombinationFederateTests.cpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/LoggingTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
  tests/helics/test_files/example_filters.json
  tests/helics/test_files/example_filters.toml
Labels: enhancement

#2215 add conditions for not including syslog
  CMakeLists.txt
  src/helics/core/BrokerBase.cpp
Labels: bug

#2216 Update path to HELICS.ico file for CPack
  .github/actions/release-build/installer-Windows.sh
  CMakeLists.txt
Labels: bug, Installation/build
