Repository GMLC-TDC/HELICS, pull requests merged in 2021-03, with the labels that each got.

#1749 Add code coverage build for HELICS 3 on GHA
  .github/workflows/code-coverage.yml
Labels: testing

#1761 Skip CI builds for automated formatting PRs/commits
  .ci/.drone.yml
  .ci/azure-pipelines.yml
  .circleci/config.yml
  .cirrus.yml
  .github/workflows/formatting.yml
  appveyor.yml
Labels: testing

#1788 Barrier check
  src/helics/core/CommonCore.cpp
  src/helics/core/FilterFederate.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/TimeDependencies.cpp
  src/helics/core/TimeDependencies.hpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
Labels: bug

#1793 add the option of ordered queries
  src/helics/application_api/BrokerApp.cpp
  src/helics/application_api/BrokerApp.hpp
  src/helics/application_api/CoreApp.cpp
  src/helics/application_api/CoreApp.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/queryFunctions.cpp
  src/helics/apps/Clone.cpp
  src/helics/apps/Recorder.cpp
  src/helics/apps/Tracer.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/Broker.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/flagOperations.hpp
  src/helics/cpp98/Broker.hpp
  src/helics/cpp98/Core.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/helics_enums.h
  src/helics/shared_api_library/helics.h
  src/helics/shared_api_library/helicsExport.cpp
  src/helics/shared_api_library/internal/api_objects.h
  tests/helics/application_api/FederateTests.cpp
  tests/helics/shared_library/QueryTests.cpp
  tests/helics/shared_library/QueryTests_cpp.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: bug, enhancement
