Repository GMLC-TDC/HELICS, pull requests merged in 2021-07, with the labels that each got.

#1993 Add missing #include <thread> to tests
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/LoggingTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/application_api/zmqSSTests.cpp
  tests/helics/apps/BrokerAppTests.cpp
  tests/helics/apps/BrokerServerTests.cpp
  tests/helics/apps/CloneTests.cpp
  tests/helics/apps/CoreAppTests.cpp
  tests/helics/apps/EchoTests.cpp
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/TracerTests.cpp
  tests/helics/core/CoreFactory-tests.cpp
  tests/helics/core/MessageTimerTests.cpp
  tests/helics/network/IPCcore_tests.cpp
  tests/helics/network/TcpCore-tests.cpp
  tests/helics/network/TcpSSCore-tests.cpp
  tests/helics/network/UdpCore-tests.cpp
  tests/helics/network/ZeromqCore-tests.cpp
  tests/helics/network/ZeromqSSCore-tests.cpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
  tests/helics/system_tests/brokerTimeoutTests.cpp
  tests/helics/system_tests/commandInterfaceTests.cpp
  tests/helics/system_tests/federateRealTimeTests.cpp
  tests/helics/system_tests/iterationTests.cpp
Labels: bug

#1996 Fix some potential issues, particularly in the python API that result…
  src/helics/core/TimeCoordinator.cpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/helicsExport.cpp
Labels: bug

#1968 Use latest gcc and clang releases for CI builds
  .ci/azure-pipelines.yml
  scripts/ci-build.sh
Labels: infrastructure/ci

#2003 Add missing #include <thread> to tests (backported)
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/LoggingTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/application_api/zmqSSTests.cpp
  tests/helics/apps/BrokerAppTests.cpp
  tests/helics/apps/BrokerServerTests.cpp
  tests/helics/apps/CloneTests.cpp
  tests/helics/apps/CoreAppTests.cpp
  tests/helics/apps/EchoTests.cpp
  tests/helics/apps/PlayerTests.cpp
  tests/helics/apps/RecorderTests.cpp
  tests/helics/apps/TracerTests.cpp
  tests/helics/core/CoreFactory-tests.cpp
  tests/helics/core/MessageTimerTests.cpp
  tests/helics/network/IPCcore_tests.cpp
  tests/helics/network/TcpCore-tests.cpp
  tests/helics/network/TcpSSCore-tests.cpp
  tests/helics/network/UdpCore-tests.cpp
  tests/helics/network/ZeromqCore-tests.cpp
  tests/helics/network/ZeromqSSCore-tests.cpp
  tests/helics/shared_library/FilterTests.cpp
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
  tests/helics/system_tests/brokerTimeoutTests.cpp
  tests/helics/system_tests/federateRealTimeTests.cpp
  tests/helics/system_tests/iterationTests.cpp
Labels: bug

#2002 Use latest gcc and clang releases for HELICS 2 CI builds
  .ci/azure-pipelines.yml
  scripts/ci-build.sh
Labels: infrastructure/ci

#2001 Fix some potential issues, particularly in the python API that result…
  src/helics/core/TimeCoordinator.cpp
  src/helics/shared_api_library/MessageFederateExport.cpp
  src/helics/shared_api_library/helicsExport.cpp
Labels: bug

#2015 HELICS 3 Release Installer CI build update
  .github/actions/interface_gen_script.sh
  .github/actions/release-build/installer-Windows.sh
  .github/actions/release-build/installer-macOS.sh
  .github/workflows/release-build.yml
  .github/workflows/static-analyzers.yml
  .github/workflows/swig-interface-gen.yml
  benchmarks/CMakeLists.txt
  config/cmake/addJsoncpp.cmake
  interfaces/octave/README.md
  scripts/_git-all-archive.sh
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: bug, infrastructure/ci

#2020 Fix HELICS 3 Interface Generating Workflow
  .github/actions/interface_gen_script.sh
  .github/workflows/swig-interface-gen.yml
  interfaces/CMakeLists.txt
  interfaces/java/CMakeLists.txt
  interfaces/java/javaSwigGenerateOnly.cmake
  interfaces/matlab/CMakeLists.txt
  scripts/generateHelicsH.py
Labels: Interfaces, bug, infrastructure/ci

#2030 Remove README in-line html details tag to fix linting error
  README.md
Labels: bug, documentation
