Repository GMLC-TDC/HELICS, pull requests merged in 2021-09, with the labels that each got.

#2089 add some fixes and tests of the json serialization and warnings fixes…
  src/helics/application_api/CombinationFederate.cpp
  src/helics/application_api/CombinationFederate.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/application_api/ValueFederateManager.hpp
  src/helics/application_api/helicsPrimaryTypes.cpp
  src/helics/core/InputInfo.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/flagOperations.hpp
  tests/helics/application_api/ValueFederateDualTransfer.cpp
  tests/helics/application_api/ValueFederateTestTemplates.hpp
  tests/helics/shared_library/PropertyIndexTests.cpp
Labels: Code Improvement

#2104 Use ASIO AsyncWriteStream and AsyncReadStream compatible functions for I/O and lowest layer socket for low level socket operations
  src/helics/network/tcp/TcpHelperClasses.cpp
  src/helics/network/tcp/TcpHelperClasses.h
Labels: enhancement

#2106 Remove fix for ASIO_ERROR_CATEGORY_NOEXCEPT definition bug affecting Boost 1.58
  src/helics/common/AsioContextManager.h
Labels: bug
