Repository GMLC-TDC/HELICS, pull requests merged in 2021-06, with the labels that each got.

#1933 add a test case and try to fix the wait for current time bug
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/network/tcp/TcpHelperClasses.cpp
  tests/helics/core/TimeCoordinatorTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
Labels: bug

#1945 update the queries added from HELICS 2
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: bug

#1950 merge documentation changes
  CHANGELOG.md
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  config/cmake/AddGoogletest.cmake
  config/cmake/addBoost.cmake
  config/cmake/addGitHooks.cmake
  config/cmake/addSpdlog.cmake
  config/cmake/addUnits.cmake
  config/cmake/addfmt.cmake
  config/cmake/addlibzmq.cmake
  docs/user-guide/advanced_topics/advanced_topics_index.md
  docs/user-guide/advanced_topics/environment_variables.md
  docs/user-guide/advanced_topics/program_termination.md
  docs/user-guide/advanced_topics/queries.md
  docs/user-guide/advanced_topics/webserver.md
  examples/CMakeLists.txt
  interfaces/java/CMakeLists.txt
  interfaces/matlab/CMakeLists.txt
  tests/CMakeLists.txt
  tests/helics/application_api/FilterTests.cpp
  tests/helics/shared_library/FilterTests.cpp
  vcpkg.json
Labels: Installation/build, documentation

#1957 Use calibreapp/image-actions@main for compressing images
  .github/workflows/compress-images.yml
Labels: infrastructure/ci

#1881 Add filter federate example documentation
  docs/img/fundamental_filter_federate_battery_SOCs.png
  docs/img/fundamental_filter_federate_charging_power.png
  docs/img/fundamental_filter_federate_estimated_SOCs.png
  docs/img/fundamental_filter_federate_federation.png
  docs/user-guide/examples/fundamental_examples/fundamental_communication.md
  docs/user-guide/examples/fundamental_examples/fundamental_filter_federate.md
  docs/user-guide/examples/fundamental_examples/fundamental_native_filter.md
Labels: documentation, ux

#1974 Federate tags
  docs/user-guide/advanced_topics/queries.md
  docs/user-guide/fundamental_topics/interface_configuration.md
  src/helics/application_api/CoreApp.cpp
  src/helics/application_api/CoreApp.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/common/JsonGeneration.hpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/fileConnections.hpp
  src/helics/core/queryHelpers.cpp
  src/helics/core/queryHelpers.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/backup/helics.h
  src/helics/shared_api_library/backup/helics_api.h
  src/helics/shared_api_library/helicsCore.h
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/common/JsonGenerationTests.cpp
  tests/helics/system_tests/QueryTests.cpp
  tests/helics/test_files/example_value_fed_testb.json
  tests/helics/test_files/example_value_fed_testb.toml
Labels: enhancement

#1979 Wait flag endpoint update
  src/helics/application_api/Federate.cpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/ForwardingTimeCoordinator.cpp
  src/helics/core/ForwardingTimeCoordinator.hpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinatorProcessing.cpp
  src/helics/core/TimeDependencies.cpp
  src/helics/core/TimeDependencies.hpp
  src/helics/core/flagOperations.hpp
  tests/helics/application_api/ValueFederateAdditionalTests.cpp
  tests/helics/apps/TracerTests.cpp
  tests/helics/core/ForwardingTimeCoordinatorTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
Labels: bug
