Repository GMLC-TDC/HELICS, pull requests merged in 2022-08, with the labels that each got.

#2410 Test resolve
  src/helics/core/Broker.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/GlobalTimeCoordinator.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeDependencies.cpp
  src/helics/core/TimeoutMonitor.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/application_api/testFixtures.cpp
  tests/helics/application_api/testFixtures.hpp
  tests/helics/sequencing_tests/Sequencing2.cpp
  tests/helics/shared_library/SystemTests.cpp
Labels: bug

#2406 Char type
  src/helics/application_api/BrokerApp.hpp
  src/helics/application_api/Endpoints.cpp
  src/helics/application_api/Endpoints.hpp
  src/helics/application_api/HelicsPrimaryTypes.hpp
  src/helics/application_api/Inputs.cpp
  src/helics/application_api/MessageFederateManager.cpp
  src/helics/application_api/Publications.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/application_api/helicsPrimaryTypes.cpp
  src/helics/application_api/helicsTypes.cpp
  src/helics/application_api/helicsTypes.hpp
  src/helics/apps/PrecHelper.cpp
  src/helics/helics_enums.h
  src/helics/shared_api_library/ValueFederateExport.cpp
  src/helics/shared_api_library/backup/helics/helics.h
  src/helics/shared_api_library/backup/helics/helics_api.h
  src/helics/shared_api_library/helicsData.cpp
  tests/helics/application_api/PrimaryTypeConversionTests.cpp
  tests/helics/shared_library/miscApiTests.cpp
Labels: Code Improvement

#2393 Publish check
  interfaces/octave/octave_maps.i
  src/helics/application_api/FederateInfo.cpp
  src/helics/application_api/helicsTypes.cpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/EndpointInfo.cpp
  src/helics/core/EndpointInfo.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/InputInfo.cpp
  src/helics/core/InputInfo.hpp
  src/helics/core/InterfaceInfo.cpp
  src/helics/core/InterfaceInfo.hpp
  src/helics/core/PublicationInfo.cpp
  src/helics/core/PublicationInfo.hpp
  src/helics/core/coreTypeOperations.cpp
  src/helics/core/flagOperations.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/helics_enums.h
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/core/FederateState-tests.cpp
  tests/helics/core/InfoClass-tests.cpp
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/dynamicFederationTests.cpp
Labels: enhancement

#2414 Add HELICS_DISABLE_C_SHARED_LIB to CMake Options
  docs/user-guide/installation/helics_cmake_options.md
Labels: documentation

#2415 Clean-up CI files and documentation related to Travis
  .travis.yml
  CONTRIBUTING.md
  README.md
  docs/developer-guide/continuous-integration.md
  scripts/cleanup-cmake.sh
  scripts/install-ci-dependencies.sh
  scripts/run-ci-tests.sh
  scripts/setup-helics-ci-options.sh
  scripts/trigger-dependent-ci-builds.sh
  scripts/upload-ci-artifact.sh
Labels: documentation, infrastructure/ci

#2417 Add encryption feature to vcpkg support
  .gitignore
  CMakeLists.txt
  vcpkg.json
Labels: enhancement

#2420 Docs v3.3
  docs/conf.py
  docs/developer-guide/docs.md
  docs/references/api-reference/index.md
  docs/references/configuration_options_reference.md
  docs/requirements.txt
  docs/user-guide/advanced_topics/queries.md
  docs/user-guide/examples/examples_index.md
  docs/user-guide/examples/supported_language_examples_index.md
  docs/user-guide/installation/index.md
  docs/user-guide/installation/installing_the_pre_compiled_libraries.md
  docs/user-guide/installation/language.md
  docs/user-guide/installation/windows.md
Labels: documentation

#2416 Change macOS Azure CI images to XCode 13 on macOS 12 and XCode 11 on macOS 11
  .ci/azure-pipelines.yml
Labels: infrastructure/ci
