Repository GMLC-TDC/HELICS, pull requests merged in 2022-09, with the labels that each got.

#2421 Change macOS Azure CI images to XCode 13 on macOS 12 and XCode 11 on macOS 11
  .ci/azure-pipelines.yml
Labels: infrastructure/ci

#2426 Test support for boost 1.80, and CMake 3.24
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  config/cmake/addBoost.cmake
  interfaces/java/CMakeLists.txt
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Installation/build

#2428 update precommit files and add an ignore file for spelling
  .pre-commit-config.yaml
  benchmarks/helics/ActionMessageBenchmarks.cpp
  config/spelling_ignorelines.txt
  docs/man/federate-apps-common-options.adoc
  docs/man/manpage_out/helics_app-clone.1
  docs/man/manpage_out/helics_app-echo.1
  docs/man/manpage_out/helics_app-player.1
  docs/man/manpage_out/helics_app-recorder.1
  docs/man/manpage_out/helics_app-source.1
  docs/man/manpage_out/helics_app-tracer.1
  docs/man/manpage_out/helics_player.1
  docs/user-guide/fundamental_topics/simulator_integration.md
  docs/user-guide/fundamental_topics/stages.md
  docs/user-guide/installation/linux.md
  src/helics/apps/Player.cpp
  src/helics/apps/helics-broker.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.hpp
Labels: Code Improvement

#2427 add a command interface to generate/clear time barriers
  docs/user-guide/advanced_topics/commandInterface.md
  docs/user-guide/advanced_topics/queries.md
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/queryHelpers.hpp
  src/helics/cpp98/Federate.hpp
  tests/helics/shared_library/timingTests_cpp.cpp
  tests/helics/system_tests/TimingTests2.cpp
Labels: enhancement

#2429 Index Groups
  docs/references/configuration_options_reference.md
  src/helics/application_api/FederateInfo.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/GlobalFederateId.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/helics_enums.h
  tests/helics/application_api/FederateTests.cpp
Labels: enhancement

#2430 Disable arm32 builds on Drone Cloud
  .ci/.drone.yml
Labels: infrastructure/ci

#2432 Maxtime tests
  src/helics/core/AsyncTimeCoordinator.cpp
  src/helics/core/BaseTimeCoordinator.cpp
  src/helics/core/BaseTimeCoordinator.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/ForwardingTimeCoordinator.cpp
  src/helics/core/ForwardingTimeCoordinator.hpp
  src/helics/core/GlobalTimeCoordinator.cpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/TimeCoordinatorProcessing.cpp
  src/helics/core/TimeDependencies.cpp
  src/helics/core/TimeDependencies.hpp
  tests/helics/core/ForwardingTimeCoordinatorTests.cpp
  tests/helics/core/TimeDependenciesTests.cpp
  tests/helics/system_tests/TimingTests.cpp
Labels: bug

#2431 Update documents for the 3.3.0 release
  CHANGELOG.md
  CMakeLists.txt
  README.md
  appveyor.yml
  docs/Public_API.md
  docs/ROADMAP.md
  docs/user-guide/advanced_topics/orchestration.md
Labels: documentation

#2436 Disable VCPKG_ROOT in GHA and Azure builds
  .ci/azure-pipelines-daily.yml
  .ci/azure-pipelines.yml
  .github/actions/benchmark-build/benchmark-Linux.sh
  .github/actions/benchmark-build/benchmark-Windows.sh
  .github/actions/benchmark-build/benchmark-macOS.sh
  .github/actions/release-build/installer-Linux.sh
  .github/actions/release-build/installer-Windows.sh
  .github/actions/release-build/installer-macOS.sh
  .github/actions/release-build/msvc-Windows.sh
  .github/actions/release-build/shared-library-Linux.sh
  .github/actions/release-build/shared-library-Windows.sh
  .github/actions/release-build/shared-library-macOS.sh
  .github/workflows/benchmark-package.yml
  .github/workflows/code-coverage.yml
  .github/workflows/msys2.yml
  CMakeLists.txt
Labels: infrastructure/ci

#2439 Sanitizer tests
  scripts/run-coverage-tests.sh
  src/helics/application_api/AsyncFedCallInfo.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/FederateInfo.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/EmptyCore.cpp
  src/helics/core/EmptyCore.hpp
  src/helics/network/NetworkCommsInterface.cpp
  tests/helics/application_api/CallbackFederateTests.cpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/core/BrokerClassTests.cpp
Labels: infrastructure/ci

#2442 Enable batching CI jobs on Azure Pipelines
  .ci/azure-pipelines.yml
Labels: infrastructure/ci
