Repository GMLC-TDC/HELICS, pull requests merged in 2022-02, with the labels that each got.

#2278 Add flags in support of encryption,
  .ci/azure-pipelines.yml
  CMakeLists.txt
  config/cmake/addlibzmq.cmake
  config/helics-config.h.in
  docs/references/configuration_options_reference.md
  docs/user-guide/advanced_topics/environment_variables.md
  scripts/setup-helics-ci-options.sh
  src/helics/helics_enums.h
  src/helics/network/NetworkBrokerData.cpp
  src/helics/network/NetworkBrokerData.hpp
  src/helics/network/NetworkCommsInterface.cpp
  src/helics/network/NetworkCommsInterface.hpp
  src/helics/network/tcp/TcpComms.cpp
  src/helics/network/tcp/TcpComms.h
  src/helics/network/tcp/TcpCommsSS.cpp
  src/helics/network/tcp/TcpCommsSS.h
Labels: enhancement

#2291 add in an additional check for the fedMonitor swap test case
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  tests/helics/application_api/LoggingTests.cpp
Labels: bug, testing

#2283 Docs8
  docs/developer-guide/style.md
  docs/introduction/hello-world-VS.md
  docs/quick-links.md
  docs/references/api-reference/Julia_API.md
  docs/references/api-reference/Python_API.md
  docs/references/api-reference/doxygen.md
  docs/references/api-reference/index.md
  docs/references/apps/App.md
  docs/references/apps/Player.md
  docs/references/apps/Source.md
  docs/references/configuration_options_reference.md
  docs/references/index.md
  docs/user-guide/advanced_topics/broker_hierarchies.md
  docs/user-guide/advanced_topics/broker_multicomputer.md
  docs/user-guide/advanced_topics/environment_variables.md
  docs/user-guide/advanced_topics/multiSourceInputs.md
  docs/user-guide/advanced_topics/profiling.md
  docs/user-guide/advanced_topics/queries.md
  docs/user-guide/advanced_topics/webserver.md
  docs/user-guide/cosim_tutorial.md
  docs/user-guide/examples/Examples.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_hierarchies.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_multibroker.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_multicomputer.md
  docs/user-guide/examples/advanced_examples/advanced_communication.md
  docs/user-guide/examples/advanced_examples/advanced_final.md
  docs/user-guide/examples/advanced_examples/advanced_manyfeds.md
  docs/user-guide/examples/advanced_examples/advanced_multi_input.md
  docs/user-guide/examples/advanced_examples/advanced_query.md
  docs/user-guide/examples/examples_index.md
  docs/user-guide/examples/fundamental_examples/fundamental_combo.md
  docs/user-guide/examples/fundamental_examples/fundamental_default.md
  docs/user-guide/examples/fundamental_examples/fundamental_endpoints.md
  docs/user-guide/examples/fundamental_examples/fundamental_fedintegration.md
  docs/user-guide/examples/fundamental_examples/fundamental_filter_federate.md
  docs/user-guide/examples/fundamental_examples/fundamental_native_filter.md
  docs/user-guide/fundamental_topics/federates.md
  docs/user-guide/fundamental_topics/filters.md
  docs/user-guide/fundamental_topics/fundamental_topics_index.md
  docs/user-guide/fundamental_topics/helics_co-sim_sequence.md
  docs/user-guide/fundamental_topics/helics_key_concepts.md
  docs/user-guide/fundamental_topics/interface_configuration.md
  docs/user-guide/fundamental_topics/logging.md
  docs/user-guide/fundamental_topics/message_federates.md
  docs/user-guide/fundamental_topics/simulator_integration.md
  docs/user-guide/fundamental_topics/timing_configuration.md
  docs/user-guide/fundamental_topics/value_federates.md
  docs/user-guide/fundamental_topics/web_interface.md
  docs/user-guide/installation/index.md
  src/docs/mainpage.dox
Labels: documentation

#2295 Switch Code Coverage job to running nightly
  .github/workflows/code-coverage.yml
  .github/workflows/release-build.yml
Labels: infrastructure/ci
