Repository GMLC-TDC/HELICS, pull requests merged in 2022-07, with the labels that each got.

#2384 Async time coordinator
  docs/references/configuration_options_reference.md
  src/helics/application_api/MessageOperators.cpp
  src/helics/core/AsyncTimeCoordinator.cpp
  src/helics/core/AsyncTimeCoordinator.hpp
  src/helics/core/BasicHandleInfo.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/HandleManager.cpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/flagOperations.hpp
  src/helics/helics_enums.h
  tests/helics/system_tests/TimingTests.cpp
Labels: enhancement, Code Improvement

#2389 Increase minimum macOS target version to 10.15
  .github/actions/setup-macos-sdk.sh
  .github/workflows/release-build.yml
Labels: Installation/build, dependencies

#2387 Interface aliases
  docs/user-guide/advanced_topics/advanced_topics_index.md
  docs/user-guide/advanced_topics/aliases.md
  src/helics/application_api/BrokerApp.cpp
  src/helics/application_api/BrokerApp.hpp
  src/helics/application_api/CoreApp.cpp
  src/helics/application_api/CoreApp.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/Broker.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/EmptyCore.cpp
  src/helics/core/EmptyCore.hpp
  src/helics/core/HandleManager.cpp
  src/helics/core/HandleManager.hpp
  src/helics/core/UnknownHandleManager.cpp
  src/helics/core/UnknownHandleManager.hpp
  src/helics/core/fileConnections.hpp
  tests/helics/application_api/CombinationFederateTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/application_api/MessageFederateKeyTests.cpp
  tests/helics/application_api/TranslatorTests.cpp
  tests/helics/application_api/ValueFederateKeyTests.cpp
  tests/helics/core/CMakeLists.txt
  tests/helics/core/HandleManagerTests.cpp
  tests/helics/test_files/combo_config.json
  tests/helics/test_files/example_combo_fed.json
  tests/helics/test_files/example_combo_fed.toml
Labels: enhancement

#2394 Try to clear up some of the remaining sporadic failures
  src/helics/application_api/MessageFederateManager.cpp
  src/helics/shared_api_library/helicsData.cpp
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/DataAPITests.cpp
  tests/helics/shared_library/loggingTests.cpp
Labels: bug

#2401 Fix swagger docs
  docs/swagger/reference/web-server.json
Labels: bug, documentation

#2403 EndpointData refactor
  src/helics/application_api/MessageFederateManager.cpp
  src/helics/application_api/MessageFederateManager.hpp
  src/helics/application_api/ValueFederateManager.cpp
  src/helics/application_api/ValueFederateManager.hpp
Labels: testing, Code Improvement

#2407 add an HELICS_STATE_UNKNOWN result to the helicsFederateGetState
  src/helics/application_api/Federate.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/api-data.h
  src/helics/shared_api_library/backup/helics/helics.h
  src/helics/shared_api_library/backup/helics/helics_api.h
  src/helics/shared_api_library/helicsCore.h
  tests/helics/shared_library/evilInputTests.cpp
Labels: Code Improvement
