Repository GMLC-TDC/HELICS, pull requests merged in 2022-05, with the labels that each got.

#2332 Sequencing fixes
  src/helics/application_api/Federate.cpp
  src/helics/core/BaseTimeCoordinator.cpp
  src/helics/core/BaseTimeCoordinator.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/ForwardingTimeCoordinator.cpp
  src/helics/core/GlobalTimeCoordinator.hpp
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeDependencies.cpp
  src/helics/core/TimeDependencies.hpp
  src/helics/core/flagOperations.hpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/sequencing_tests/CMakeLists.txt
  tests/helics/sequencing_tests/Sequencing1.cpp
  tests/helics/sequencing_tests/Sequencing2.cpp
Labels: bug

#2333 Warning fixes 3 2
  CMakeLists.txt
  config/cmake/addSpdlog.cmake
  config/cmake/addfmt.cmake
  src/helics/application_api/BrokerApp.hpp
  src/helics/core/BaseTimeCoordinator.cpp
  src/helics/core/BaseTimeCoordinator.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/Core.hpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/SmallBuffer.hpp
  src/helics/core/TimeCoordinator.hpp
  src/helics/core/TranslatorFederate.cpp
  src/helics/shared_api_library/MessageFiltersExport.cpp
  src/helics/shared_api_library/TranslatorExport.cpp
  tests/helics/core/ActionMessage-tests.cpp
  tests/helics/sequencing_tests/Sequencing1.cpp
  tests/helics/sequencing_tests/Sequencing2.cpp
  tests/helics/shared_library/timingTests_cpp.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: Code Improvement

#2350 Fix typo in HELICS_DEPRECATED macro name
  scripts/generateHelicsH.py
Labels: bug

#2360 bug fix on iteration, enter executing mode, and wait for current time flag
  src/helics/core/TimeCoordinator.cpp
  src/helics/core/TimeDependencies.cpp
  src/helics/core/TimeDependencies.hpp
  tests/helics/system_tests/iterationTests.cpp
Labels: bug

#2348 look at the failures in the log buffer tests
  tests/helics/application_api/LoggingTests.cpp
  tests/helics/system_tests/QueryTests.cpp
Labels: bug

#2354 update the formatting for some enumerations to match the standard
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreTypes.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/FilterFederate.cpp
  src/helics/core/FilterFederate.hpp
  src/helics/core/TimeCoordinatorProcessing.cpp
  src/helics/core/TimeoutMonitor.cpp
  src/helics/core/TranslatorFederate.cpp
  src/helics/core/TranslatorFederate.hpp
  src/helics/network/CommsInterface.cpp
  src/helics/network/CommsInterface.hpp
  src/helics/network/inproc/InprocComms.cpp
  src/helics/network/ipc/IpcComms.cpp
  src/helics/network/tcp/TcpComms.cpp
  src/helics/network/tcp/TcpCommsSS.cpp
  src/helics/network/test/TestComms.cpp
  src/helics/network/udp/UdpComms.cpp
  src/helics/network/zmq/ZmqComms.cpp
  src/helics/network/zmq/ZmqCommsSS.cpp
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/core/BrokerClassTests.cpp
  tests/helics/core/FederateState-tests.cpp
Labels: Code Improvement

#2362 Coverage builds
  .github/workflows/code-coverage.yml
  scripts/run-circleci-tests-sanitizer.sh
  scripts/run-circleci-tests.sh
  scripts/run-coverage-tests.sh
  tests/helics/application_api/FilterAdditionalTests.cpp
  tests/helics/application_api/FilterTests.cpp
  tests/helics/system_tests/TimingTests2.cpp
Labels: Installation/build

#2365 Fix some exception handling paths when dealing with very long file na…
  src/helics/application_api.hpp
  src/helics/common/TomlProcessingFunctions.cpp
  src/helics/common/TomlProcessingFunctions.hpp
  src/helics/helics.hpp
  src/helics/helics_enums.h
  src/helics/shared_api_library/backup/helics/helics.h
  src/helics/shared_api_library/backup/helics/helics_api.h
  tests/helics/application_api/FederateTests.cpp
  tests/helics/test_files/extra_files_testing_for_very_long_file_paths/this_is_a_ridiculously_long_file_name_to_test_some_odd_conditions_in_the_toml_parser_so_we_need_a_long_file_name.toml
Labels: bug

#2357 Iteration example
  docs/user-guide/advanced_topics/advanced_topics_index.md
  docs/user-guide/advanced_topics/iteration.md
  docs/user-guide/examples/advanced_examples/advanced_examples_index.md
  docs/user-guide/examples/advanced_examples/advanced_iteration.md
Labels: documentation, Examples
