Repository GMLC-TDC/HELICS, pull requests merged in 2022-03, with the labels that each got.

#2290 Fix missing timing dependency when subscribing from an endpoint
  src/helics/core/FederateState.cpp
  tests/helics/system_tests/TimingTests2.cpp
Labels: bug

#2296 Remove VS2017 CI builds and add a VS2022 build
  .ci/azure-pipelines.yml
  .github/workflows/release-build.yml
  docs/developer-guide/ci-cd-infrastructure.md
  docs/developer-guide/continuous-integration.md
  docs/user-guide/installation/language.md
  docs/user-guide/installation/windows.md
Labels: infrastructure/ci

#2303 Update HELICS options for network tests and helics_broker build location
  src/helics/apps/CMakeLists.txt
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/zmqSSTests.cpp
  tests/helics/apps/MultiBrokerTests.cpp
  tests/helics/network/InprocCore-Tests.cpp
  tests/helics/system_tests/ErrorTests.cpp
  tests/helics/system_tests/networkTests.cpp
Labels: bug, testing

#2304 Add encryption related CI tests
  tests/helics/CMakeLists.txt
  tests/helics/network/networkInfoTests.cpp
  tests/helics/system_tests/CMakeLists.txt
  tests/helics/system_tests/networkTests.cpp
  tests/helics/test_files/encryption_config/multiBroker_encrypted_bridge.json.in
  tests/helics/test_files/encryption_config/openssl.json.in
  tests/helics/test_files/encryption_config/openssl_certs/ca.pem
  tests/helics/test_files/encryption_config/openssl_certs/dh4096.pem
  tests/helics/test_files/encryption_config/openssl_certs/server.pem
  tests/helics/test_files/encryption_config/openssl_certs/ssl_encryption_config.json.in
Labels: testing

#2306 Combo file test for CPP98
  src/helics/application_api/ValueFederate.cpp
  src/helics/cpp98/Federate.hpp
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/test-combo-federate_cpp.cpp
  tests/helics/shared_library/test-message-federate_cpp.cpp
  tests/helics/test_files/combo_config.json
Labels: bug

#2308 resolve some undefined behavior in certain edge cases
  src/helics/core/BasicHandleInfo.cpp
  src/helics/core/BasicHandleInfo.hpp
  src/helics/core/GlobalFederateId.hpp
  src/helics/core/HandleManager.cpp
  src/helics/core/HandleManager.hpp
Labels: bug

#2320 Fix pre-commit markdown linting errors on Windows installation doc file
  docs/user-guide/installation/windows.md
Labels: bug, documentation

#2310 Update Docker images and migrate builds to GitHub Actions
  .github/actions/docker/develop_docker.sh
  .github/actions/docker/main_docker.sh
  .github/actions/docker/release_docker.sh
  .github/actions/docker/test_docker.sh
  .github/workflows/docker.yml
  config/Docker/Dockerfile-HELICS
  config/Docker/Dockerfile-HELICS-apps
  config/Docker/Dockerfile-HELICS-builder
  src/helics/core/CommonCore.hpp
  src/helics/core/FilterFederate.hpp
Labels: infrastructure/ci

#2316 Add documentation on options for more complex networking environments
  docs/references/configuration_options_reference.md
  docs/user-guide/advanced_topics/broker_hierarchies.md
  docs/user-guide/advanced_topics/broker_multicomputer.md
  docs/user-guide/advanced_topics/commandInterface.md
  docs/user-guide/advanced_topics/networking.md
Labels: documentation

#2319 Use external libraries
  CMakeLists.txt
  config/cmake/addJsoncpp.cmake
  config/cmake/addSpdlog.cmake
  config/cmake/addUnits.cmake
  config/cmake/addfmt.cmake
  docs/user-guide/installation/helics_cmake_options.md
  src/helics/application_api/Inputs.cpp
  src/helics/application_api/Publications.cpp
  src/helics/common/CMakeLists.txt
  src/helics/core/InputInfo.cpp
Labels: bug, enhancement, dependencies

#2321 Fix missing submodule source code in the HELICS release source archive
  scripts/_git-all-archive.sh
Labels: bug, Installation/build, infrastructure/ci

#2324 update CLi11 to release 2.2
  ThirdParty/helics/external/CLI11/CLI11.hpp
Labels: dependencies
