Repository GMLC-TDC/HELICS, pull requests merged in 2022-01, with the labels that each got.

#2254 Docs5 - change image links to helics_docs_resources
  docs/user-guide/advanced_topics/architectures.md
  docs/user-guide/advanced_topics/broker_hierarchies.md
  docs/user-guide/advanced_topics/orchestration.md
  docs/user-guide/co-simulation_overview.md
  docs/user-guide/deprecated/deprecated_material_dump.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_hierarchies.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_multibroker.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_multicomputer.md
  docs/user-guide/examples/advanced_examples/advanced_brokers_simultaneous.md
  docs/user-guide/examples/advanced_examples/advanced_default.md
  docs/user-guide/examples/advanced_examples/advanced_examples_index.md
  docs/user-guide/examples/advanced_examples/advanced_multi_input.md
  docs/user-guide/examples/advanced_examples/advanced_orchestration.md
  docs/user-guide/examples/advanced_examples/advanced_query.md
  docs/user-guide/examples/fundamental_examples/fundamental_combo.md
  docs/user-guide/examples/fundamental_examples/fundamental_default.md
  docs/user-guide/examples/fundamental_examples/fundamental_endpoints.md
  docs/user-guide/examples/fundamental_examples/fundamental_examples_index.md
  docs/user-guide/examples/fundamental_examples/fundamental_fedintegration.md
  docs/user-guide/examples/fundamental_examples/fundamental_filter_federate.md
  docs/user-guide/examples/fundamental_examples/fundamental_native_filter.md
  docs/user-guide/fundamental_topics/federates.md
  docs/user-guide/fundamental_topics/filters.md
  docs/user-guide/fundamental_topics/helics_key_concepts.md
  docs/user-guide/fundamental_topics/message_federates.md
  docs/user-guide/fundamental_topics/simulator_integration.md
  docs/user-guide/fundamental_topics/timing_configuration.md
  docs/user-guide/fundamental_topics/timing_exercise.md
  docs/user-guide/fundamental_topics/timing_exercise_answers.md
  docs/user-guide/fundamental_topics/value_federates.md
  docs/user-guide/fundamental_topics/web_interface.md
  docs/user-guide/installation/index.md
  docs/user-guide/installation/language.md
Labels: documentation

#2255 Time monitor
  ThirdParty/frozen/map.h
  ThirdParty/frozen/random.h
  docs/references/configuration_options_reference.md
  docs/user-guide/advanced_topics/commandInterface.md
  docs/user-guide/advanced_topics/queries.md
  docs/user-guide/fundamental_topics/logging.md
  src/helics/core/BrokerBase.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/GlobalFederateId.hpp
  src/helics/core/TimeCoordinatorProcessing.cpp
  src/helics/core/TimeoutMonitor.cpp
  tests/helics/application_api/LoggingTests.cpp
Labels: enhancement

#2256 Log buffer
  docs/references/configuration_options_reference.md
  docs/user-guide/advanced_topics/queries.md
  docs/user-guide/fundamental_topics/logging.md
  src/helics/application_api/FederateInfo.cpp
  src/helics/common/CMakeLists.txt
  src/helics/common/LogBuffer.cpp
  src/helics/common/LogBuffer.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/helics_definitions.hpp
  src/helics/core/loggingHelper.hpp
  src/helics/helics_enums.h
  src/helics/shared_api_library/backup/helics/helics.h
  src/helics/shared_api_library/backup/helics/helics_api.h
  tests/helics/application_api/LoggingTests.cpp
  tests/helics/system_tests/brokerTimeoutTests.cpp
Labels: enhancement

#2266 Update Linux install and comboFed examples - hotfix main
  docs/user-guide/installation/linux.md
  examples/comboFederates1/comboFed.cpp
  examples/comboFederates1/run.sh
  examples/comboFederates1/run3.sh
Labels: documentation

#2262 Process comms
  examples/comboFederates1/comboFed.cpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CommonCore.hpp
  src/helics/core/Core.hpp
  src/helics/core/CoreTypes.hpp
  src/helics/core/EmptyCore.cpp
  src/helics/core/EmptyCore.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/TimeCoordinatorProcessing.cpp
  src/helics/cpp98/Federate.hpp
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/backup/helics/helics.h
  src/helics/shared_api_library/backup/helics/helics_api.h
  src/helics/shared_api_library/helicsCore.h
  tests/helics/application_api/LoggingTests.cpp
Labels: enhancement

#2261 Remote log
  docs/user-guide/advanced_topics/commandInterface.md
  docs/user-guide/advanced_topics/queries.md
  docs/user-guide/fundamental_topics/logging.md
  src/helics/apps/MultiBroker.cpp
  src/helics/common/CMakeLists.txt
  src/helics/common/logging.cpp
  src/helics/common/logging.hpp
  src/helics/core/ActionMessage.hpp
  src/helics/core/ActionMessageDefintions.hpp
  src/helics/core/BrokerBase.cpp
  src/helics/core/BrokerBase.hpp
  src/helics/core/CMakeLists.txt
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/CoreBroker.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/FederateState.hpp
  src/helics/core/GlobalFederateId.hpp
  src/helics/core/LogManager.cpp
  src/helics/core/LogManager.hpp
  src/helics/core/TimeoutMonitor.cpp
  src/helics/core/loggingHelper.hpp
  src/helics/network/inproc/InprocComms.cpp
  src/helics/network/mpi/MpiComms.cpp
  src/helics/network/test/TestComms.cpp
  src/helics/network/zmq/ZmqComms.cpp
  src/helics/network/zmq/ZmqCommsSS.cpp
  tests/helics/application_api/LoggingTests.cpp
Labels: enhancement, Code Improvement

#2272 Fix C API doc strings that break RTD website theme
  src/helics/shared_api_library/MessageFederate.h
  src/helics/shared_api_library/helicsCore.h
Labels: documentation
