Repository GMLC-TDC/HELICS, pull requests merged in 2022-06, with the labels that each got.

#2368 Data api additions
  CMakeLists.txt
  src/helics/cpp98/CMakeLists.txt
  src/helics/cpp98/DataBuffer.hpp
  src/helics/cpp98/Federate.hpp
  src/helics/cpp98/Translator.hpp
  src/helics/shared_api_library/CMakeLists.txt
  src/helics/shared_api_library/ValueFederateExport.cpp
  src/helics/shared_api_library/backup/helics/helics.h
  src/helics/shared_api_library/backup/helics/helics_api.h
  src/helics/shared_api_library/helicsData.cpp
  src/helics/shared_api_library/helicsData.h
  tests/helics/CMakeLists.txt
  tests/helics/find_package_tests/CMakeLists.txt
  tests/helics/package_config_tests/CMakeLists.txt
  tests/helics/shared_library/CMakeLists.txt
  tests/helics/shared_library/DataAPITests.cpp
Labels: enhancement

#2371 Large iteration count test
  src/helics/core/TimeCoordinator.cpp
  tests/helics/system_tests/iterationTests.cpp
Labels: bug

#2377 fix some warnings and leaks from overnight tests
  src/helics/application_api/Inputs.hpp
  src/helics/network/zmq/ZmqCommsCommon.cpp
  src/helics/shared_api_library/ValueFederateExport.cpp
  tests/helics/shared_library/DataAPITests.cpp
  tests/helics/shared_library/SystemTests.cpp
  tests/helics/system_tests/iterationTests.cpp
Labels: bug

#2382 Fetch submodules using actions/checkout for scheduled Code Coverage build
  .github/workflows/code-coverage.yml
Labels: bug, infrastructure/ci

#2379 long_file_name_removal
  tests/helics/application_api/CMakeLists.txt
  tests/helics/application_api/FederateTests.cpp
  tests/helics/test_files/extra_files_testing_for_very_long_file_paths/this_is_a_ridiculously_long_file_name_to_test_some_odd_conditions_in_the_toml_parser_so_we_need_a_long_file_name.toml
Labels: bug

#2380 test case fixes
  tests/helics/application_api/CombinationFederateTests.cpp
  tests/helics/application_api/MessageFederateAdditionalTests.cpp
  tests/helics/sequencing_tests/Sequencing1.cpp
Labels: bug
