Repository GMLC-TDC/HELICS, pull requests merged in 2023-01, with the labels that each got.

#2493 tweak the exec check when using wait for current time flag
  src/helics/core/TimeDependencies.cpp
  tests/helics/system_tests/commandInterfaceTests.cpp
Labels: bug

#2495 Setup dependabot to update github-actions
  .github/dependabot.yml
Labels: infrastructure/ci

#2497 Add documentation on encrypted communication
  CHANGELOG.md
  docs/user-guide/advanced_topics/advanced_topics_index.md
  docs/user-guide/advanced_topics/encrypted_communication.md
  docs/user-guide/orientation.md
  src/helics/application_api/FederateInfo.cpp
  tests/helics/test_files/encryption_config/openssl_certs/ssl_encryption_config.json.in
Labels: documentation

#2498 Remove Drone CI badge from the README
  README.md
Labels: documentation
