Repository GMLC-TDC/HELICS, pull requests merged in 2024-12, with the labels that each got.

#2707 Fix compile error when building without HELICS Apps
  src/helics/shared_api_library/helicsAppsExportNull.cpp
Labels: bug

#2680 Cloning filter documenation
  docs/conf.py
  docs/developer-guide/index.md
  docs/index.md
  docs/references/apps/Connector.md
  docs/references/configuration_options_reference.md
  docs/references/index.md
  docs/references/publications.md
  docs/user-guide/advanced_topics/advanced_topics_index.md
  docs/user-guide/advanced_topics/connector_fed.md
  docs/user-guide/examples/advanced_examples/advanced_async_time_request.md
  docs/user-guide/examples/advanced_examples/advanced_examples_index.md
  docs/user-guide/examples/advanced_examples/advanced_helics_connector.md
  docs/user-guide/examples/fundamental_examples/fundamental_endpoints.md
Labels: documentation

#2715 Update daily Azure pipelines builds to use Ubuntu 22.04 container image
  .ci/azure-pipelines-daily.yml
Labels: infrastructure/ci

#2720 update to work with boost 1.87
  config/cmake/addBoost.cmake
  src/helics/apps/helicsWebServer.cpp
  tests/helics/webserver/webServerWebSocketTests.cpp
Labels: Installation/build

#2719 Add check for exported_symbols_list linker option on macOS
  src/helics/shared_api_library/CMakeLists.txt
Labels: Installation/build
