Repository GMLC-TDC/HELICS, pull requests merged in 2024-01, with the labels that each got.

#2583 Update boost
  CMakeLists.txt
  ThirdParty/cmake/ucm.cmake
  config/cmake/addBoost.cmake
Labels: dependencies

#2560 Translator config
  .circleci/tsan_suppression.txt
  docs/references/configuration_options_reference.md
  src/helics/application_api/Endpoints.cpp
  src/helics/application_api/Endpoints.hpp
  src/helics/application_api/Federate.cpp
  src/helics/application_api/Federate.hpp
  src/helics/application_api/Filters.cpp
  src/helics/application_api/Filters.hpp
  src/helics/application_api/MessageFederate.cpp
  src/helics/application_api/MessageFederate.hpp
  src/helics/application_api/Translator.cpp
  src/helics/application_api/Translator.hpp
  src/helics/application_api/ValueFederate.cpp
  src/helics/application_api/ValueFederate.hpp
  src/helics/common/addTargets.hpp
  src/helics/core/CommonCore.cpp
  src/helics/core/TranslatorFederate.cpp
  tests/helics/application_api/FederateInfoTests.cpp
  tests/helics/application_api/FederateTests.cpp
  tests/helics/application_api/TranslatorTests.cpp
  tests/helics/test_files/ControllerConfig.json
  tests/helics/test_files/example_translators.json
  tests/helics/test_files/example_translators.toml
  tests/helics/test_files/invalid_translator_operation.json
  tests/helics/test_files/unusual_filters.toml
Labels: enhancement

#2599 resolves issue #2572
  CMakeLists.txt
  config/cmake/AddGoogletest.cmake
  config/cmake/addSpdlog.cmake
  config/cmake/addfmt.cmake
  src/helics/application_api/typeOperations.cpp
  src/helics/application_api/typeOperations.hpp
  src/helics/core/coreTypeOperations.hpp
  src/helics/core/helicsCLI11.hpp
  src/helics/core/helicsVersion.cpp
  src/helics/core/helicsVersion.hpp
  src/helics/shared_api_library/.clang-tidy
  src/helics/shared_api_library/helicsExport.cpp
  tests/helics/core/CoreFactory-tests.cpp
Labels: bug

#2588 Fix workflow artifacts
  .github/workflows/benchmark-package.yml
  .github/workflows/release-build.yml
Labels: bug, infrastructure/ci, github_actions
