Repository GMLC-TDC/HELICS, pull requests merged in 2024-02, with the labels that each got.

#2606 Trigger helics-packaging workflows using workflow_dispatch
  .github/workflows/release-build.yml
Labels: infrastructure/ci

#2604 add some additional stuff to debug failing loggingTests.cpp
  src/helics/shared_api_library/.clang-tidy
  src/helics/shared_api_library/FederateExport.cpp
  src/helics/shared_api_library/helicsCallbacks.cpp
  src/helics/shared_api_library/helicsCore.h
  tests/helics/shared_library/QueryTests.cpp
  tests/helics/shared_library/QueryTests_cpp.cpp
  tests/helics/shared_library/loggingTests.cpp
Labels: testing

#2607 Check if helicsCpp98_ide target exists before modifying properties
  src/helics/CMakeLists.txt
Labels: bug

#2592 Connector app
  docs/references/apps/Connector.md
  src/helics/application_api/CoreApp.hpp
  src/helics/application_api/HelicsPrimaryTypes.hpp
  src/helics/application_api/helicsPrimaryTypes.cpp
  src/helics/apps/CMakeLists.txt
  src/helics/apps/Connector.cpp
  src/helics/apps/Connector.hpp
  src/helics/apps/appMain.cpp
  src/helics/apps/connectorMain.cpp
  src/helics/core/ActionMessage.cpp
  src/helics/core/CommonCore.cpp
  src/helics/core/CoreBroker.cpp
  src/helics/core/EndpointInfo.cpp
  src/helics/core/EndpointInfo.hpp
  src/helics/core/FederateState.cpp
  src/helics/core/HandleManager.hpp
  src/helics/core/InterfaceInfo.cpp
  src/helics/core/InterfaceInfo.hpp
  src/helics/core/UnknownHandleManager.cpp
  src/helics/core/UnknownHandleManager.hpp
  src/helics/core/queryHelpers.hpp
  tests/helics/application_api/EndpointLinkingTests.cpp
  tests/helics/apps/CMakeLists.txt
  tests/helics/apps/Connector2StageTests.cpp
  tests/helics/apps/ConnectorFileTests.cpp
  tests/helics/apps/ConnectorTagTests.cpp
  tests/helics/apps/ConnectorTests.cpp
  tests/helics/apps/ConnectorTests2.cpp
  tests/helics/apps/test_files/connector/cascade.txt
  tests/helics/apps/test_files/connector/simple-quotes.txt
  tests/helics/apps/test_files/connector/simple.json
  tests/helics/apps/test_files/connector/simple.txt
  tests/helics/apps/test_files/connector/simple_tags.txt
Labels: enhancement

#2615 update CLI11 to release 2.4.1
  ThirdParty/helics/external/CLI11/CLI11.hpp
  src/helics/apps/helicsApp.cpp
Labels: dependencies
